### ISSUE TITLE
Disabling episode file induces a WARNING log during build

### ISSUE THREAD

**Issue by boskoop** [highsource/maven-jaxb2-plugin#107]
When turning off the episode file in the project configuration, the build log contains a warn-log "Episode file is not writable, could not add if-exists attributes".
```xml
	<plugin>
		<groupId>org.jvnet.jaxb2.maven2</groupId>
		<artifactId>maven-jaxb2-plugin</artifactId>
		<configuration>
			<episode>false</episode>
		</configuration>
	</plugin>
```
The log appears during the generate-phase:
```
[INFO] --- maven-jaxb2-plugin:0.13.2-SNAPSHOT:generate (generate) @ maven-jaxb2-plugin-tests-gh-issue-107 ---
[INFO] Up-to-date check for source resources [[file:/example/maven-jaxb2-plugin/tests/gh-issue-107/src/main/resources/purchaseorder.xsd, file:/example/maven-jaxb2-plugin/tests/gh-issue-107/pom.xml]] and target resources [[]].
[INFO] Sources are not up-to-date, XJC will be executed.
[WARNING] Episode file [/example/maven-jaxb2-plugin/tests/gh-issue-107/target/generated-sources/xjc/META-INF/sun-jaxb.episode] is not writable, could not add if-exists attributes.
[INFO]
```
I think this was introduced with #55 where `setupEpisodeHackForUnusedSchemaBindings()` only checks whether the episode file is writeable, but not if it's turned off at all.

This can be fixed pretty easy by simply adding a check at said place.

I will provide a demo project/pull request asap.

**Comment by highsource** [comment]
Should be fixed now.

**Comment by samodadela** [comment]
This should be fixed, but I'm still getting the error... I have:
```
                <configuration>
                    <extension>true</extension>
                    <noFileHeader>true</noFileHeader>
                    <episode>false</episode>
```

Plugin version:
```

**Comment by gavvvr** [comment]
I confirm that the bug is still present with 0.14.0

**Comment by gavvvr** [comment]
@laurentschoelens Unfortunately, I can't check this, because I no longer have the codebase with `jaxb-maven-plugin`

**Comment by laurentschoelens** [comment]
> @laurentschoelens Unfortunately, I can't check this, because I no longer have the codebase with `jaxb-maven-plugin`

Thanks for your reply
I'll wait and close the issue if no more feedback since warning is not longer present
