### ISSUE TITLE
Generated sources not added to the build path with version 0.13.1 on Eclipse Neon.2 Release (4.6.2)

### ISSUE THREAD

**Issue by bnjdpn** [highsource/maven-jaxb2-plugin#109]
`pom.xml` : 
```
	<build>
		<plugins>
			<plugin>
				<groupId>org.jvnet.jaxb2.maven2</groupId>
				<artifactId>maven-jaxb2-plugin</artifactId>
				<version>${maven-jaxb2-plugin.version}</version>
				<executions>
					<execution>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<generateDirectory>${project.build.directory}/generated-sources/jaxb</generateDirectory>
					<schemaDirectory>src/main/resources/xsd</schemaDirectory>
					<generatePackage>com.foo.bar.pojo</generatePackage>
				</configuration>
			</plugin>
		</plugins>
	</build>
```

After a `mvn clean install` with `<maven-jaxb2-plugin.version>0.12.1</maven-jaxb2-plugin.version>`, no problem. The `genared-sources` folder is added to the build path : 
![image](https://cloud.githubusercontent.com/assets/6208889/22241994/f22467c2-e221-11e6-9a60-2c040ce4c0e8.png)

With `<maven-jaxb2-plugin.version>0.13.1</maven-jaxb2-plugin.version>` : 
I got an error on the <execution> in the `pom.xml` : `Execution default of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.1:generate failed: A required class was missing while executing org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.1:generate: com/sun/xml/bind/api/ErrorListener`
And the `genared-sources` folder is not added to the build path : 
![image](https://cloud.githubusercontent.com/assets/6208889/22242185/b972975e-e222-11e6-99e2-97e0120f2c2f.png)

**Comment by highsource** [comment]
Please try 0.13.2.

**Comment by APoole00** [comment]
I am seeing the same issue. I am running Eclipse Oxygen 4.7.0 and 0.13.2.

**Comment by AnuroopSirothia** [comment]
This is Eclipse issue and not maven-jaxb2-plugin issue. Start Eclipse using JDK instead of JRE. For example, in eclipse.ini make sure you have an entry like shown below:-

`-vmC:\Program Files\Java\jdk1.8.0_101\bin\javaw.exe-startup` instead of JRE. Hope this solves the problem.

**Comment by ssparasuram** [comment]
After starting Eclipse using JDK , it works fine for me.
I was using Ecplise Version: Oxygen.2 Release (4.7.2)

**Comment by Rafael-Simonelli** [comment]
Had the same issue, the project was fine and compiling, until the bug came out of nowhere. With Eclipse Oxygen. Upgraded to version 0.14.0 and it is working fine.

**Comment by Ravikanthreddy** [comment]
0.14.0 plugin solved it

**Comment by highsource** [comment]
As I understand, the problem no longer persists.

**Comment by praveen-anjha** [comment]
Hi 
I am generating schema different folder but not able to add in build path only XJC is added in build path not others  
![4Ajec](https://user-images.githubusercontent.com/56357828/67770352-219f6c80-fa4e-11e9-95d2-c669020d8a13.png)

Please advise how to add other two xjc08 and xjc09

**Comment by highsource** [comment]
@praveen-anjha Please file a new issue and post your `pom.xml`.
