### ISSUE TITLE
Can jaxb generate swagger annotations?

### ISSUE THREAD

**Issue by shmerskawven07** [highsource/maven-jaxb2-plugin#115]
Hi,
In my project I generate java dto from xsd thanks to maven-jaxb2-plugin.

example of generated dto :

@XmlRootElement(name = "createItem")
public class CreateItem {

@XmlElement(required = true)
@NotNull
protected String name;
}

I generate a swagger documentation but the description remains empty. I'm looking for a solution to add description to swagger documentation.

In a static java dto I would simply add @ApiModelProperty and it works but since my java classes are generated by jaxb if I add @ApiModelProperty it will be deleted.

Can Jaxb generate swagger annotations like @ApiModelProperty?

I found this "https://github.com/redlab/swagger-jaxb" which work fine for me but the problem this for codehause jaxb plugin.

Can you please help? Another solution is more than welcome...

**Comment by highsource** [comment]
You can use JAXB plugins independent of which Maven JAXB plugin you use. So this swagger-jaxb thing should work with maven-jaxb2-plugin as well.

**Comment by shmerskawven07** [comment]
I tried but it does not work

**Comment by highsource** [comment]
What exactly did not work? Please post your `pom.xml` and `mvn -X clean install`.

**Comment by shmerskawven07** [comment]
does not Work : 

`
 <plugin>
						<groupId>org.jvnet.jaxb2.maven2</groupId>
						<artifactId>maven-jaxb2-plugin</artifactId>
						<version>0.13.0</version>
						<executions>
<execution>
						<id>order-schema</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<arguments>-swaggerify</arguments>
							<schemaDirectory>${project.basedir}/src/main/resources/xsd/orders/orders/</schemaDirectory>
							<schemaIncludes>
								<include>*.xsd</include>
							</schemaIncludes>
							<generatePackage>com.ppp.mmm.orders</generatePackage>
							<generateDirectory>${project.build.directory}/generated-sources/orders</generateDirectory>
						</configuration>
					</execution>
</executions>
						
						<dependencies>
					<dependency>
						<groupId>javax.xml.parsers</groupId>
						<artifactId>jaxp-api</artifactId>
						<version>1.4.5</version>
					</dependency>
					<dependency>
						<groupId>com.sun.xml.parsers</groupId>
						<artifactId>jaxp-ri</artifactId>
						<version>1.4.5</version>
					</dependency>
					<dependency>
						<groupId>com.sun.xml.bind</groupId>
						<artifactId>jaxb-impl</artifactId>
						<version>2.2.11</version>
					</dependency>
					<dependency>
						<groupId>com.sun.xml.bind</groupId>
						<artifactId>jaxb-xjc</artifactId>
						<version>2.2.11</version>
					</dependency>
					<dependency>
						<groupId>com.sun.xml.bind</groupId>
						<artifactId>jaxb-core</artifactId>
						<version>2.2.11</version>
					</dependency>
					<dependency>
						<groupId>be.redlab.jaxb</groupId>
						<artifactId>swagger-jaxb</artifactId>
						<version>1.5</version>
					</dependency>
				</dependencies>`


This works : 

<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>jaxb2-maven-plugin</artifactId>
						<version>1.5</version>
						<executions>
<execution>
						<id>order-schema</id>
						<goals>
							<goal>xjc</goal>
						</goals>
						<configuration>
							<arguments>-swaggerify</arguments>
							<schemaDirectory>${project.basedir}/src/main/resources/xsd/orders/orders/</schemaDirectory>
							<schemaIncludes>
								<include>*.xsd</include>
							</schemaIncludes>
							<generatePackage>com.ppp.mmm.orders</generatePackage>
							<generateDirectory>${project.build.directory}/generated-sources/orders</generateDirectory>
						</configuration>
					</execution>
</executions>
						
						<dependencies>
					<dependency>
						<groupId>javax.xml.parsers</groupId>
						<artifactId>jaxp-api</artifactId>
						<version>1.4.5</version>
					</dependency>
					<dependency>
						<groupId>com.sun.xml.parsers</groupId>
						<artifactId>jaxp-ri</artifactId>
						<version>1.4.5</version>
					</dependency>
					<dependency>
						<groupId>com.sun.xml.bind</groupId>
						<artifactId>jaxb-impl</artifactId>
						<version>2.2.11</version>
					</dependency>
					<dependency>
						<groupId>com.sun.xml.bind</groupId>
						<artifactId>jaxb-xjc</artifactId>
						<version>2.2.11</version>
					</dependency>
					<dependency>
						<groupId>com.sun.xml.bind</groupId>
						<artifactId>jaxb-core</artifactId>
						<version>2.2.11</version>
					</dependency>
					<dependency>
						<groupId>be.redlab.jaxb</groupId>
						<artifactId>swagger-jaxb</artifactId>
						<version>1.5</version>
					</dependency>
				</dependencies>`


 I'm trying to get the "<arguments>-swaggerify</arguments>" to work.

Parent dependencies : 
`<dependencies>
		<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-annotations</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>`

**Comment by shmerskawven07** [comment]
sorry not used to github :s 

to resume :

To resume ,this example here ; https://github.com/krasa/krasa-jaxb-tools-example/tree/master/maven-jaxb2-plugin, does work but if I changed the plugin to "org.jvnet.jaxb2.maven2/maven-jaxb2-plugin
/0.13.0" it does not work.

**Comment by highsource** [comment]
Please check the docs on how to configure the plugin.

* https://github.com/highsource/maven-jaxb2-plugin/wiki/Configuration-Cheat-Sheet
* https://github.com/highsource/maven-jaxb2-plugin/wiki/Using-JAXB-Plugins

You have basically switched `groupId` and `artifactId` and left all the configuration intact. This does not work that way, these are completely different plugins written by different people. You should not expect plugin configuration to be portable across plugins.

**Comment by shmerskawven07** [comment]
Here is the POM : https://github.com/redlab/swagger-jaxb-tck/blob/master/swagger-jaxb-it-generate/pom.xml

I want to get this example to work for org.jvnet.jaxb2.maven2/maven-jaxb2-plugin/0.13.0

**Comment by highsource** [comment]
> I want to get this example to work for org.jvnet.jaxb2.maven2/maven-jaxb2-plugin/0.13.0

Well, you'll have to port the configuration. Here's a link to the documentation:

https://github.com/highsource/maven-jaxb2-plugin/wiki
