### ISSUE TITLE
Ability to Skip generation of source files

### ISSUE THREAD

**Issue by broot02** [highsource/maven-jaxb2-plugin#116]
Looking through the configuration options I am not seeing a way to skip generation of sources - either at an execution level, or a global plugin level? Is there a way to achieve this behavior?

Basically the scenario we have is that we want to generate source files, but we also want the ability to modify these source files, say custom annotations for example(just an example). If the source files are being regenerated at every clean & build we can't achieve this. An alternative we can use is basically just generate and comment this execution out, not ideal but can be done.

If there is no way to skip the generation process for select executions, global plugin level. Is there a reason why this functionality would be opposed?

**Comment by highsource** [comment]
No, there's no configuration option to disable the plugin. 

> Looking through the configuration options I am not seeing a way to skip generation of sources - either at an execution level, or a global plugin level? Is there a way to achieve this behavior?

Primarily with up-to-date checks:
https://github.com/highsource/maven-jaxb2-plugin/wiki/Up-To-Date-Checks
The code will only be regenerated if certain source files change. But it is intended for normal use-cases like "do not recompile schemas unless *.xsd files changed".

> Basically the scenario we have is that we want to generate source files, but we also want the ability to modify these source files

You should not modify the generated source code or store in a version control system. If you do, it is a wrong thing to do.

> say custom annotations for example(just an example).

See [jaxb2-annotate-plugin](https://github.com/highsource/jaxb2-annotate-plugin) for this example.

> If the source files are being regenerated at every clean & build we can't achieve this.

They should be and you should not be able to achieve this.
