### ISSUE TITLE
xs:import issue

### ISSUE THREAD

**Issue by TeoChas** [highsource/maven-jaxb2-plugin#117]
I am using 
<groupId>org.jvnet.jaxb2.maven2</groupId>
<artifactId>maven-jaxb2-plugin</artifactId>
<version>0.13.2</version>

 But i have an very critical issue. In my xsd file I have 
<xs:import namespace="http://www.example/1.0" schemaLocation="http://www.example/1.0/example.xsd> 

Follow error occurs : 
 lineNumber: 4; columnNumber: 123; schema_reference.4: Failed to read schema document...
 because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
XSD file is an online file no maven repo exists to use schema configurations also <schema><url> doesn't work.  I have seen also that : http://stackoverflow.com/questions/26296654/how-can-i-generate-classes-from-outside-xsd-file-using-jaxb-xjc
but nothing seems to be ok

**Comment by highsource** [comment]
And you are absolutely sure that the schema you reference via `schemaLocation` exists?

If nothing helps, you can save your resource locally and use a catalog file to rewrite the imported URL:

https://github.com/highsource/maven-jaxb2-plugin/wiki/Using-Catalogs

**Comment by teo89** [comment]
I am sure that exists because if I hit URL, XSD file display online. Also with other plugins imported XSD files exists. But I would prefer to use maven-jaxb2-plugin because of extra configurations.  I have already read about catalogs but I don't want to have locally all included XSD files. Is there any configuration except catalog. 
Thank you in advance

**Comment by highsource** [comment]
The question is why it cannot be downloaded from the plugin then. Run `mvn clean install -X` and post the log. Maybe you're behind a proxy?

**Comment by teo89** [comment]
Yes I am behind a proxy but in my settings.xml file proxy is set. Also I added useActiveProxyAsHttpproxy to true. With mvn clean install -X command get follow:
DEBUG] Parent resolver has resolved publicId [http://www.example/1.0], systemId [http://www.example/1.0/example.xsd] to [null].
[DEBUG] SystemId [http://example2/0.1/example.xsd] is not a Maven dependency resource URI. Returning parent resolver result [null].
I have two questions 
 Why all imported xsd URLs resolve to null?
Also Following errors displayed. That means that I am ok with import and now binding issues occurred? 
[ERROR] Error while parsing schema(s).Location [ http://example2/0.1/example.xsd{653,25}].
com.sun.istack.SAXParseException2; systemId: http://example2/0.1/example.xsd; lineNumber: 653; columnNumber: 25; Property "Rows" is already defined. Use &lt;jaxb:property> to resolve this conflict.
        at com.sun.tools.xjc.ErrorReceiver.error(ErrorReceiver.java:86)

lineNumber: 685; columnNumber: 44; The following location is relevant to the above error
lineNumber: 232; columnNumber: 71; Property "Title" is already defined. Use &lt;jaxb:property> to resolve this conflict.
lineNumber: 219; columnNumber: 36; The following location is relevant to the above error

**Comment by highsource** [comment]
You previously said that you were getting this error:

> lineNumber: 4; columnNumber: 123; schema_reference.4: Failed to read schema document...

I don not see it in your log.

> Why all imported xsd URLs resolve to null?

This is just debug info that there was no special resolution of these URLs. In this case the original URL is used.

> That means that I am ok with import and now binding issues occurred?

Yes.

**Comment by teo89** [comment]
Set useActiveProxyAsHttpproxy to true solve all the issues.  Thank you for your help
