### ISSUE TITLE
sun-jaxb.episode has header even with <noFileHeader>true</noFileHeader>

### ISSUE THREAD

**Issue by pauloneves** [highsource/maven-jaxb2-plugin#122]
Even if I set <noFileHeader>true</noFileHeader>, the sun-jaxb.episode is generated with a header.

I know that generated files shouldn't be in version control, but we decided to do it in our project. This is creating unnecessary commits.

**Comment by highsource** [comment]
This is a problem in XJC, not in the `maven-jaxb2-plugin`. The plugin just passes the setting to XJC.
This is not something I can fix, please report to JAXB team.

**Comment by highsource** [comment]
And you should really not be checking generated files into VCS.
