### ISSUE TITLE
Getting Duplicate class error using maven-jaxb2 plugin

### ISSUE THREAD

**Issue by sharmanaveen** [highsource/maven-jaxb2-plugin#124]
I am using the maven-jaxb2- plugin version 0,13,2 jdk 1.8 having multiple schemas like a.xsd ,b.xsd.c.xsd having there respective bindings a.xjb.b.xjb .All the schema ,bindings are located at the same path.The generatedDirectory is different for each and and have removed the forceRegenate tag.Now when trying to compile I am getting the duplicate class error for Objectfactory.java. Any suggestions as how to proceed or what things need to be taken care in this scenario

**Comment by poireauxvinaigrette** [comment]
I ve got the same error since 2.3, only on Jenkins build

**Comment by highsource** [comment]
You have to specify different target packages for each of the schemas.

**Comment by sharmanaveen** [comment]
The target packages are defined different but getting Duplicate class error for ObjectFactory.java. Is there any way by which we can stop the generation of this class or ignore it specifically .The delete task will does not work in this scenario

**Comment by highsource** [comment]
By *target packages* I mean Java packages which are used when your code is generated. You can specify this in `pom.xml` as `generatePackage` (I don't recommend this) or via bindings, that corresponds to your number 2.

In number 1 you probably refer to targert directory, this has nothing to do with packages.

> Apart from that if I have started experiencing this issues only after removing the tag as specified in the Best Practices.

If you have multiple executions, you have to use separate target directories.

If I understand you correctly:

> 2.Now in the bindings file a.xjb and b.xjb they are pointing to the same package
> <jaxb:package name="com.test.check"> in a.xjb
> and same in b.xjb file
> <jaxb:package name ="com.test.check"> in b.xjb

Then it seems you use the same target package in different schemas (i.e. for different namespaces). You can't do that, you have to use different packages for different namespaces for JAXB to work correctly.

> I cannot make change in the package name in binding file as If I do make a change in that it will break all the existing functionality

I am afraid I don't see many options here.

> Please do let me know if there is any way to move ahead or any example that can be referred to

I don't see any easy solutions here. What I'd recommend is that you fix you bindings to use different target packages for different schemas/namespaces. This is the only reasonable course of action. I can think of a couple of further options, but they are not practical and are hacky.
