### ISSUE TITLE
Modular Schema / Defeated by schemaLocation

### ISSUE THREAD

**Issue by buko** [highsource/maven-jaxb2-plugin#127]
Are there any examples of modular schema production lying around?

I feel like I'm close but it's still not quite working. Spent several hours on this and any help. I have a basic multi-module project:

project/
   a-schema/
      src/main/resources/schema/
         a.xsd
         a.xjb
     pom.xml
 b/
     src/main/resources/schema
        b.xsd
        b.xjb
   pom.xml

The b schema project depends on a schema project. 

The b schema explicitly depends on a schema project using the episode feature.

This works -- except the a.xjb binding schema is ignored. The types in b don't get any of the sweet XMLAdapters that have been defined in a.xjb.

Add an explicit binding reference to the a.xjb file using dependencyResource syntax in b-schema/pom.xml.

<binding>							
	<dependencyResource>
		<groupId>project</groupId>
		<artifactId>a-schema</artifactId>
		<resource>schema/a.xjb</resource>
							</dependencyResource>
						</binding>

Now a.xjb gets discovered but an error is generated:

systemId: maven:project:a-schema:jar::!/schema/a.xjb; lineNumber: 18; columnNumber: 69; "a.xsd" is not a part of this compilation. Is this a mistake for "http://www.w3.org/2001/xml.xsd"?

Try as I might I can't work around this.

I've tried using the schema-catalog and adding something like:

REWRITE_SYSTEM "a.xsd" "maven:com.project:a-schema!/schema/a.xsd"

Still no dice. Any ideas? When I'm pulling in a binding from a dependency resource how do I resolve relative schemaLocations in that binding file?

**Comment by highsource** [comment]
Here is an example of a highly modular project.

https://github.com/highsource/ogc-schemas

It is, indeed, somewhat tricky. What I normally do is this:

* Create a module with all your schemas as resources.
* Create one module per (logical) schema.
* In this module, compile the schema from an absolute URL. If you happen to have some actual schema registry (a-la http://schemas.opengis.net/), use an absolute schema URL from that registry. If you don't have anything like this, just invent an URL - it does not actually need to exist.
* Configure a catalog file rewriting your absolute URLs to resources in the schema module. Like `REWRITE_SYSTEM "http://schemas.opengis.net" "maven:org.jvnet.ogc:ogc-schemas:jar::!/ogc"`
* In your binding files reference schemas via absolute URLs.

With these tricks you can completely avoid relative URLs. Still, your builds will work offline/network independent because your schemas will be rewritten to local resources via catalog file.

Hope this helps.

**Comment by buko** [comment]
It makes sense but how do you get the plugin to actually respect the schema catalog when processing your XJB file?

In XJB you might have:

<jaxb:bindings schemaLocation="http://example.com/2017/a.xsd" node="/xs:schema">

In schema_catalog.cat you have:

REWRITE_SYSTEM "http://example.com/2017/test/text-common.xsd" "maven:com.project.a:a-schema!/a.xsd"

If you compile this the system complains that "http://example.com/2017/a.xsd" is not part of the compilation.

It seems like the schema catalog is ignored when resolving schemaLocation?

**Comment by buko** [comment]
Ah, ok, so you can't rewrite a URL to a maven resource to yourself since you're not your own dependency. I'll try now to put schemas into a separate project.

**Comment by buko** [comment]
I feel like I'm close but this is still not quite working.

I'm now seeing what appears to be double binding errors of the form:

> [ERROR] Error while parsing schema(s).Location [ jar:file:/C:/Users/ocean/.m2/repository/com/bubblegumproject/polis/polis-common-schema-binding/0.0.1-SNAPSHOT/polis-common-schema-binding-0.0.1-SNAPSHOT.jar!/jaxb-bindings/polis-common.xjb{20,24}].
com.sun.istack.SAXParseException2; systemId: jar:file:/C:/Users/ocean/.m2/repository/com/bubblegumproject/polis/polis-common-schema-binding/0.0.1-SNAPSHOT/polis-common-schema-binding-0.0.1-SNAPSHOT.jar!/jaxb-bindings/polis-common.xjb; lineNumber: 20; columnNumber: 24; Multiple <schemaBindings> are defined for the target namespace "urn:schemas-polis:common"

The problem is that one binding for the namespace comes from the polis-common.xjb. Through this bindings come for the various JAXB adapters. 

Another binding comes from the sun-jaxb.episode file:

> [ERROR] Error while parsing schema(s).Location [ jar:file:/C:/Users/ocean/.m2/repository/com/bubblegumproject/polis/polis-common-schema-binding/0.0.1-SNAPSHOT/polis-common-schema-binding-0.0.1-SNAPSHOT.jar!/META-INF/sun-jaxb.episode{22,65}].
com.sun.istack.SAXParseException2; systemId: jar:file:/C:/Users/ocean/.m2/repository/com/bubblegumproject/polis/polis-common-schema-binding/0.0.1-SNAPSHOT/polis-common-schema-binding-0.0.1-SNAPSHOT.jar!/META-INF/sun-jaxb.episode; lineNumber: 22; columnNumber: 65; Another <schemaBindings> is defined here

Note there shouldn't be much overlap between these two.

Any ideas how to work around this?

**Comment by highsource** [comment]
> It seems like the schema catalog is ignored when resolving schemaLocation?

No, it is not.

> Ah, ok, so you can't rewrite a URL to a maven resource to yourself since you're not your own dependency. 

Well, almost. There's just no JAR artifact to resolve to (yet).

> Any ideas how to work around this?

Sorry, it is quite hard to give any advice judging just on the vague description of your project structure and binding files. I really suggest that you check the https://github.com/highsource/ogc-schemas project, you may get a couple of ideas from there.

I think the "Multiple are defined for the target namespace" problem should only come from multiple `schemaBindings` definitions bound to the same namespace. (I can't tell for sure as I don't know what stands in your binding files.) If this is correct then why do you need `schemaBindings` for you adapters? I thought they are defined in `globalBindings`?

**Comment by buko** [comment]
Thanks for all your help.

When you get the chance please take a look at https://github.com/buko/scrum4j-model.

It's a smaller, sample project that encapsulates what we're trying to do.

For some reason... it works. Our main project is still failing in all kinds of very strange ways.

It's not so pretty but so far what we've seen is that to do modular compilation you need to:

* Put schema and bindings files in their own projects.
* Bindings, as you said, must refer to their schemas using absolute URLs.
* In the bindings pom file you've got to refer to the schema using an absolute URL. (Took us a long while to figure that out to make it work.)
* Don't use xsd:import. This breaks the plugin in very strange ways. It leads to duplicate definitions. Instead in each module we include the schema from all its dependencies.
* We ran into some issues with transitive dependencies. They don't really transitive. Each binding project must include the schema and binding for all other projects.
* Don't use schemaBindings in the xjb files. schemaBindings combined with episodic complation leads to all sorts of strange issues. Instead we finally got that project working by switching all the bindings projects to using generatePackage.

The next big challenges:

* How to incorporate globalBindings? It seems you can't use globalBindings and modular compilation.
* How to use https://github.com/highsource/w3c-schemas/tree/master/xlink and https://github.com/highsource/w3c-schemas/tree/master/xhtml? We'd really like to incorporate xhtml and xlink into our schema but we were running into all sorts of duplicate definitions and duplicate bindings before. Will try again on the simpler scrum4j project.

**Comment by buko** [comment]
Added support for global bindings and for use of xlink. (Again transitive deps don't quite work and xlink must be added to every module.)

Everything *finally* works and the build is very fast. 

The nice thing about this system is that it's not necessary to put all schemas in one project.

This might be a useful example for others.
