### ISSUE TITLE
Unknown Protocol: maven when referring to a catalog that doesn't exist

### ISSUE THREAD

**Issue by buko** [highsource/maven-jaxb2-plugin#129]
In the POM file for the binding project if you mistakenly refer to a catalog dependency that doesn't exist:

```xml
<catalogs>
 <catalog>
  <dependencyResource>
    <groupId>com.example.oops</groupId>
    <artifactId>my-schema</artifactId>
    <resource>xml/catalogs/my-catalogs.xml</resource>
   </depdencyResource>
</catalog>
</catalogs>
```
The groupId is wrong. Instead of `com.example.oops` it should be `com.example.schema`.

The build fails with a very strange error that doesn't reveal much about the actual issue -- the catalogDependencyResource doesn't exist. The error looks like this:

```
[ERROR] Failed to execute goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.1:generate (generate-sources) on project uia-datatypes-schema-binding: Error parsing catalog [maven:com.bubblegumproject.uia:uia-datatypes-schema:jar::!/xml/catalogs/uia-datatypes-catalog.xml]. unknown protocol: maven -> [Help 1]
```

Would recommend that this error message be changed to something more informative that points the way to the real issue. As it is it's very confusing and it took a while to figure out what was actually going on.

**Comment by highsource** [comment]
Continued in xjc-maven-plugin/xjc23#6.
