### ISSUE TITLE
useDependenciesAsEpisodes=true tries to interpret pom artifacts as bindings.

### ISSUE THREAD

**Issue by UnasZole** [highsource/maven-jaxb2-plugin#130]
Hi,

As described in the doc, setting useDependenciesAsEpisodes=true works fine if all dependencies are jars : only jars containing a META-INF/sun-jaxb.episode are taken into account.

However, if there is a pom dependency discovered (visible as it will be listed in "[INFO] episodeFiles (resolved):" output), then compilation will fail when trying to read it as an xjb binding : 
[ERROR] Error while parsing schema(s).Location [ file:/D:/m2repo/path/to/artifact-1.9.9.pom{2,202}].
org.xml.sax.SAXParseException; systemId: file:/D:/m2repo/path/to/artifact-1.9.9.pom; lineNumber: 2; columnNumber: 202; Unexpected <project> appears at line 2 column 202

useDependenciesAsEpisodes should ignore pom dependencies !

**Comment by highsource** [comment]
Continued in xjc-maven-plugin/xjc23#5.
