### ISSUE TITLE
Using transitive dependency on dependencyResource

### ISSUE THREAD

**Issue by xvil** [highsource/maven-jaxb2-plugin#132]
I have multi-module maven project where some modules are using other modules as dependencies.

Let's say module A has a (direct) dependency to module B which, in turn, has a direct dependency to module C.

I use transitive dependencies feature from Maven.
As module C is a transitive dependency of module B, I don't need (and don't want actually) to mention it as an explicit dependency of module A.

I am building JAXBs using episodes and catalogs.

In module A, I make references to catalogs that exist in both module B and module C artifacts like that:
```
<catalogs>
   <catalog>
	   <dependencyResource>
		   <groupId>org.myproject</groupId>
		   <artifactId>module-b</artifactId>
		   <resource>catalog/catalog.cat</resource>
	   </dependencyResource>
   </catalog>
   <catalog>
	   <dependencyResource>
		   <groupId>org.myproject</groupId>
		   <artifactId>module-c</artifactId>
		   <resource>catalog/catalog.cat</resource>
	   </dependencyResource>
   </catalog>
</catalogs>
```
As module-b artifact is a direct dependency, I don't need to specify the version (it is found in the dependency section of the pom file).
But for module-c, I apparently need to do it.  I expected not to because it is a transitive dependency of module-b.  I wanted to rely on the specific version of module-c module-b depends on instead of having to specify (and know) the specific version of module-c that the version of modules-b I use depends on.

Is this way of working not currently supported by the plugin or am I missing something there?
If it is not, would it be possible to include such a feature in some upcoming release of the plugin?
I guess it would be enough to check the transitive dependency chain of all the explicitly mentioned dependencies of the current module.
In case of a version conflict somewhere against the same maven artifact, the version would be manually mentioned in the proper dependencyResource.

I hope this all makes sense.

Of course, for now, I can work with specifying the version of the transitive dependency but I'd rather avoid it in the future.

Thanks for any help.

**Comment by highsource** [comment]
I think this should work right now.

**Comment by xvil** [comment]
Thanks!

Do you mean using 0.13.3-SNAPSHOT or 0.13.2 (which I am using currently)?

**Comment by highsource** [comment]
0.13.2. If this does not work please PR a test project somewhere under https://github.com/highsource/maven-jaxb2-plugin-support.

**Comment by xvil** [comment]
I created a sample project that exhibits the issue I am facing as a PR under https://github.com/highsource/maven-jaxb2-plugin-support as requested.

**Comment by highsource** [comment]
Please check the latest snapshot.

**Comment by xvil** [comment]
Is there an online repo where I can find it or should I build it?
Building it (from master) gives me errors in MAVEN_JAXB2_PLUGIN-53:b

**Comment by highsource** [comment]
You should build it. Never mind test projects.

**Comment by xvil** [comment]
OK then.
Tested in both my sample project and my actual one: glad to report that you fixed the issue! :)

When is 0.13.3 scheduled for release?
