### ISSUE TITLE
What do I need to add if I use the HTTPS protocol?

### ISSUE THREAD

**Issue by JiangSongBai** [highsource/maven-jaxb2-plugin#133]
Such as title.

**Comment by highsource** [comment]
If your JDK trusts your HTTPS connection - nothing.
If you have a self-signed certificate or other some fancy certificate that you JDK does not trust, you may need to pin that certificate in your JDK.

In any case, this is not in scope of this plugin as it simply relies on the underlying JDK mechanisms for networking.

I also *do not recommend* compiling online resources. Make a local copy of your schemas and use episodes to rewrite URLs. Everything else will make your builds fragile.
