### ISSUE TITLE
A way to override CatalogManager instead of using sun internal

### ISSUE THREAD

**Issue by bertramn** [highsource/maven-jaxb2-plugin#135]
Hi @highsource, any chance we could update [RawXJC2Mojo.java](https://github.com/highsource/maven-jaxb2-plugin/blob/7cd632c9d4fd1900c5473f4fff642b78b72e7e58/plugin-core/src/main/java/org/jvnet/jaxb2/maven2/RawXJC2Mojo.java#L843) to allow discovery or override of the catalog manager? The sun internal one is not ideal in some situations. Cheers Niels

**Comment by highsource** [comment]
Sure, open for PR.

**Comment by highsource** [comment]
Continued in xjc-maven-plugin/xjc23#4.
