### ISSUE TITLE
WS  SOAP with Authorization no stub generation

### ISSUE THREAD

**Issue by thiagomoreira-luizalabs** [highsource/maven-jaxb2-plugin#138]
Hello, there is a webservice in soap that requires a header with authorization, in pom.xml I did not find any tags related to this purpose, I need to generate the stubs.

**Comment by highsource** [comment]
There are none and there will be none.
You should save a local copy of the schema you want to compile and use catalogs to rewrite URLs to the local copy.
https://github.com/highsource/maven-jaxb2-plugin/wiki/Using-Catalogs
