### ISSUE TITLE
Issue with xml validation against xml schema file with online imported xml schema files

### ISSUE THREAD

**Issue by teo89** [highsource/maven-jaxb2-plugin#139]
In my XML schema, many online XML schemas are imported in. When I generated the Java classes everything worked fine. But when I tried to make the validation of an XML against XML schema with the following code: 
   
      URL url = MachineXMLServiceImpl.class.getResource(xsdFilePath);
      SchemaFactory sf = SchemaFactory.newInstance(XMLConstants.W3C_XML_SCHEMA_NS_URI);
      Schema schema = sf.newSchema(url);
      
      JAXBContext jaxbContext;
      jaxbContext = JAXBContext.newInstance(Class.forName(className));

      Unmarshaller unmarshaller = jaxbContext.createUnmarshaller();
      unmarshaller.setSchema(schema);
      unmarshaller.unmarshal(xmlReader);
The following error occurred. 
Invalid XML file. An issue occurred in parsing with the following error message. 

org.xml.sax.SAXParseException: src-resolve: Cannot resolve the name 'type_from_import_online_xml_schema' to a(n) 'element declaration' component. 

I tried to download all the online imported XML schemas but these are more than forty XML schemas. So the first issue and question is the following one. Can we download automatically all the referred XML schemas locally? 

Secondly I tried to use a catalog.xml file to rewrite the schemaLocation to my local XML schemas files path. But the same XML schema can be imported in other XML schema too, as a result I need to have two relative paths for the same XML schema for example 
```
<rewriteSystem systemIdStartString="http://testUrl/1.0" rewritePrefix="../testUrl/1.0"/>
<rewriteSystem systemIdStartString="http://testUrl/1.0" rewritePrefix="../../testUrl/1.0"/>
```
How can I have a general relative path for an XML schema?

Any other solution it would be  welcome too.

**Comment by highsource** [comment]
What you ask is not in the scope of the `maven-jaxb2-plugin`.

**Comment by teo89** [comment]
What about the part of catalog.xml file. Can I have multiple catalog.xml files for a certain XML schema( or group of XML schema files)? If not, how can I rewrite a URL with two different values?

**Comment by highsource** [comment]
> If not, how can I rewrite a URL with two different values?

You can't. And you should not need to.

Don't get me wrong but what you're asking is not in the scope of `maven-jaxb2-plugin`. It is related to the runtime usage of JAXB/schema validation, not to schema compilation which this project focuses on. Even if I could, I don't have resources to help everybody with all JAXB-related things whatsoever.

Please ask on StackOverflow.
