### ISSUE TITLE
s4s-elt-character in generation of Java classes 

### ISSUE THREAD

**Issue by teo89** [highsource/maven-jaxb2-plugin#140]
When I use in catalog.xml file the rewrite to the path "targetName/../relative_local_path" the following error during the building for the generation of java classes occurred. 
`s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]'.`
I read the issue ["Allow rewriting system ids for local files #19"](https://github.com/highsource/maven-jaxb2-plugin/issues/19) but the jar files isn't a possible solution for us.

**Comment by highsource** [comment]
Your problem is likely that the URL you rewrite to does not return an XML schema. It looks like some JavaScript.

> I read the issue "Allow rewriting system ids for local files #19" but the jar files isn't a possible solution for us.

Why?

**Comment by teo89** [comment]
The URL is the URL of an XML schema. I tried to use absolute path to the XML schema file also but the same error occurred.

**Comment by highsource** [comment]
Well, *something* returns `(function(i,s,o,g,r,a,m)` and so on for that URL. So apparently it is not an URL of an XML Schema.
