### ISSUE TITLE
Regeneration is not properly executed after clean

### ISSUE THREAD

**Issue by super-horst** [highsource/maven-jaxb2-plugin#141]
I noticed that regeneration is not performed properly if the target/generated-sources has been created earlier in the same maven run.
Before running _maven-jaxb2-plugin_, I execute the _jaxws-maven-plugin_ which creates target/generated-sources during the same goal and puts it's code in there.

During the same maven generate-sources run I get the log:

    [INFO] --- maven-jaxb2-plugin:0.13.3:generate (XMLSec) @ myProject ---
    [INFO] Latest timestamp of the source resources is [2017-11-17 11:23:47.783], earliest timestamp of the target resources is [2017-11-17 11:23:48.844].
    [INFO] Sources are up-to-date, XJC will be skipped.

Indicating there is nothing to do while actually nothing is there. A workaround is to execute _maven-jaxb2-plugin_ before _jaxws-maven-plugin_.

    <plugin>
	    <groupId>org.jvnet.jaxb2.maven2</groupId>
	    <artifactId>maven-jaxb2-plugin</artifactId>
	    <version>0.13.3</version>
	    <executions>
    		<execution>
			    <id>XMLSec</id>
    			    <goals>
				    <goal>generate</goal>
			    </goals>
			    <configuration>
    				<catalog>${basedir}/src/main/resources/xenc/catalog.cat</catalog>
				    <strict>false</strict>
				    <laxSchemaValidation>true</laxSchemaValidation>
				    <schemaIncludes />
				    <schemas>
    					<schema>
						    <fileset>
    							<directory>${basedir}/src/main/resources/xenc/</directory>
							    <includes>
    								<include>xenc-schema-11.xsd</include>
							    </includes>
						    </fileset>
					    </schema>
				    </schemas>
				    <generateDirectory>target/generated-sources</generateDirectory>
			    </configuration>
		    </execution>
	    </executions>
    </plugin>

**Comment by highsource** [comment]
The best is probably use different output directories for different plugins in order not to mix generated code.

Also see https://github.com/highsource/maven-jaxb2-plugin/wiki/Up-To-Date-Checks. You can configure `depends`/`produces` to include only files which are relevant to/produced by `maven-jaxb2-plugin` generation. Bu still, the easiest is to use separate output directores.

**Comment by super-horst** [comment]
Thanks for the link, I've been able to make it work with the `produces` tag
