### ISSUE TITLE
How can I stop second execution to clean the common generate directory? I want to generate source of all executions in src/main/java directory.

### ISSUE THREAD

**Issue by jaraws** [highsource/maven-jaxb2-plugin#142]
I have two subsequent executions defined in POM, both with their own binding file and xsds. As I can see there are few classes  which are generated by first execution are later got deleted. And when it comes to the execution of second schema it throws compiler  error for the class generated during the execution of second schema.
Execution 1 config: ----------
<configuration>
							<schemaDirectory>${project.basedir}/src/main/resources/wsdl/Eligibility/1.0</schemaDirectory>
							<schemaIncludes>
								<include>EligibilityService_1.xsd</include>
							</schemaIncludes>
							<bindingDirectory>${project.basedir}/src/main/resources/binding</bindingDirectory>
							<bindingIncludes>
								<include>EligibilityService_1_Binding.xjb</include>
							</bindingIncludes>
							<generateDirectory>${project.basedir}/src/main/java</generateDirectory>
							<forceRegenerate>true</forceRegenerate>
						</configuration>

Execution2 config:------------
<schemaDirectory>${project.basedir}/src/main/resources/wsdl/FeeChargeComission/1.0/</schemaDirectory>
							<schemaIncludes>
								<include>FCCService_1_0.xsd</include>
							</schemaIncludes>
							<bindingDirectory>${project.basedir}/src/main/resources/binding</bindingDirectory>
							<bindingIncludes>
								<include>FCCService_1_Binding.xjb</include>
							</bindingIncludes>
							<generateDirectory>${project.basedir}/src/main/java</generateDirectory>
							<forceRegenerate>true</forceRegenerate>

Plugin used:
<groupId>org.jvnet.jaxb2.maven2</groupId>
				<artifactId>maven-jaxb2-plugin</artifactId>
				<version>0.13.3</version>
Thanks

**Comment by jaraws** [comment]
I have gone through the link but in my case there are many xsds which are imported by the 2 main xds of these 2 executions which are common in both of them. Hence, therefore, lots of generated classes will be common among the generated directories of both the executions. I am not sure how good would that be to have 100s of common classes in two different directories.

What I am looking for is that let the second execution over write the classes which are common among both the executions along with its own unique classes. 

Considering in this project there will be no code written by the developers; I added src/main/java as generate directory from the code readability perspective when build is triggered in IDE.

**Comment by mgainty** [comment]
highsource is correct..
what if you need to clean the directory (generated/src/main/java) before you generate java from xsd?
NEVER put test or generated code into the projects source directory of src/main/java

**Comment by highsource** [comment]
@jaraws
IDEs don't care if it is `src/main/java` or `target/generated-sources/xjc1` or whatever. If the configuration is fine, IDEs will pick the source directories from Maven config. So it is really better to follow the convention.

There's a `removeOldOutput` and `cleanPackageDirectories` configuration elements which might be close to what you want, but this is no what I'd do.

However, the "right" way to do what you want is more complicated. If you want to avoid duplicated classes, you should compile one logical schema per Maven module and then use them as dependencies/episodes in depending schemas. Take a look at the [OGC Schemas Project](https://github.com/highsource/ogc-schemas). It compiles a huge number of schemas, effectively producing one JAR per logical schema. These JARs are used as episodes so if some schema B depends on A, classes for A are not generated when B is compiled.
