### ISSUE TITLE
No classes generated

### ISSUE THREAD

**Issue by jegjessing** [highsource/maven-jaxb2-plugin#144]
I'm calling a WSDL on a URL on my local machine.
If I do this using Chrome I see the following headers:

> Connection:Keep-Alive
Content-Encoding:gzip
Content-language:da
Content-Length:1559
Content-Type:text/xml; charset=UTF-8
Date:Thu, 08 Feb 2018 10:07:07 GMT
ETag:
Keep-Alive:timeout=5, max=100
Last-Modified:Thu, 08 Feb 2018 09:57:40 GMT
Server:Apache/2.4.18 (Ubuntu)
Vary:Accept,Accept-Encoding`
I can run wsimport just fine, it parses the WSDL and generates all the 1502 files, phew...
So the WSDL works...

But when running clean compile I get:

> [WARNING] The URI [http://www.tinglysningwsdl.test/service/binding/administration/1/Brugerformular?wsdl] seems to represent an absolute HTTP or HTTPS URL. Getting the last modification timestamp is only possible if the URL is accessible and if the server returns the [Last-Modified] header correctly. This method is not reliable and is likely to fail. In this case the last modification timestamp will be assumed to be unknown.
[INFO] Sources are not up-to-date, XJC will be executed.
[INFO] Episode file [/home/jgj/Documents/FDC/client/target/generated-sources/xjc/META-INF/sun-jaxb.episode] was augmented with if-exists="true" attributes.
And ONLY the .episode is created :-(

**Comment by highsource** [comment]
If your server returns `Last-Modified`, you can safely ignore the warning. The logs also say that generation will be executed so the warning has nothing to do with the problem.

I don't know why no classes are generated. From my experience, XJC compilation of WSDL generally does not produce good results since XJC basically only compiles the schema.

**Comment by quider** [comment]
Yep, i have the same problem. Classes are not generated. Just sun-jaxb.episode in target.

**Comment by highsource** [comment]
@quider See above. Nothing is generated if there's nothing to generate.
