### ISSUE TITLE
Upgrade to JAXB 2.3.1, avoid illegal access to internal APIs

### ISSUE THREAD

**Issue by nicolaiparlog** [highsource/maven-jaxb2-plugin#148]
Running the Maven JAXB2 Plugin on Java 9 or later, leads to the following warning by the JVM:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector (file:/home/parlog/.m2/repository/org/glassfish/jaxb/jaxb-runtime/2.3.0/jaxb-runtime-2.3.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

This happens because `org.glassfish.jaxb : jaxb-runtime : 2.3.0` uses reflection to access `ClassLoader::defineClass`. This is allowed by default in Java 9 (although it leads to a warning), but could be denied by default as early as in Java 11 (although I consider that to be unlikely).

I assume there isn't much Maven-JAXB2-Plugin can do about this except to track that dependency and update as soon as possible. Or could there be an alternative implementation that doesn't need `ClassLoader::defineClass`?

**Comment by nicolaiparlog** [comment]
In case this is a problem for any user, a possible fix (for the warning, but also for future errors) is to add a file `.mvn/jvm.config` to the Maven project's root directory and add the following line:

```
--add-opens java.base/java.lang=ALL-UNNAMED
```

**Comment by nicolaiparlog** [comment]
[This StackOverflow question](https://stackoverflow.com/q/50237516/2525313) seems relevant.

**Comment by matejsp** [comment]
JAXB illegal reflective access is fixed in latest released version 2.3.1. It was released in October but it was very late pushed to maven central. https://mvnrepository.com/artifact/org.glassfish.jaxb/jaxb-runtime/2.3.1

This should be resolved after jaxb version bump in pom.xml: <jaxb23.version>2.3.1</jaxb23.version>

**Comment by highsource** [comment]
@matejsp Thanks for notifying.

**Comment by highsource** [comment]
@nicolaiparlog  @matejsp Would you please give the current `0.14.1-SNAPSHOT` a try? Before I release it?

**Comment by matejsp** [comment]
I have build and checked the 0.14.1-SNAPSHOT. It works as advertised on Java 11 and maven 3.6.0.

When building the plugin I am just getting a bunch of:

> Artifact Ids of the format maven-___-plugin are reserved for
plugins in the Group Id org.apache.maven.plugins
Please change your artifactId to the format ___-maven-plugin
In the future this error will break the build.

But I guess you already know that :)

**Comment by highsource** [comment]
> But I guess you already know that :)

Yes. Please see #26.

**Comment by mdiskin** [comment]
Is the snapshots still available? I'm not able to location them anymore.

**Comment by solovees** [comment]
Push the fixed version in the central repository, please

**Comment by bertramn** [comment]
@highsource any chance you could release the plugin with JAXB 2.3.1 dependencies? We have to resort to sorcery to override the plugin dependencies, which is verbose and unneeded. Many thanks Niels

**Comment by highsource** [comment]
@bertramn It's not ready yet, sorry. Will work on the new release but I'm pretty short on resources at the moment.

**Comment by lexsoto** [comment]
I see this ticket is closed, but was a fix released?  I can't find version 0.14.1 in Maven central and I am still getting the warnings with version 0.14.0

**Comment by mattrpav** [comment]
** should be updated to more recent jaxb-runtime v2.3.2

**Comment by krys86** [comment]
Hello, 
there is no 0.14.1 version in maven central and the warnings are still present.

The 0.14.0 version of "maven-jaxb2-plugin" is based on a parent project that still use the jaxb 2.3.0 version.

Would it be possible to fix it please?

Java version : AdoptOpenJDK (build 11.0.5+10)

BR
Cristiano

**Comment by divStar** [comment]
Hello,
amazing plugin here! I am in love with it - and I really love how well-documented it is!

This aside: I am also experiencing this warning and while I do not terribly mind (since it works), I assume this shouldn't be happening.

I use `jakarta.xml.bind` and `AdoptOpenJDK 11.0.5 (2019-10-15)` (I know I should update, but I don't actually develop much in Java at the moment at home).
```
		<dependency>
			<groupId>jakarta.xml.bind</groupId>
			<artifactId>jakarta.xml.bind-api</artifactId>
			<version>2.3.3</version>
		</dependency>
```

I could turn off the warning, but I suppose I should not. Do you have an idea what to do?
