### ISSUE TITLE
Not generating sources and not getting error with version 0.13.3

### ISSUE THREAD

**Issue by fer1979** [highsource/maven-jaxb2-plugin#150]
Hi, 

Trying to generate sources from the next wsdl but not getting error, just not generating sources. The version I am using is 0.13.3.  Just creating me the file sun-jaxb.episode. I suspect it can be a bug in the xjc because the wsdl does not have any "types" or "xsd". The log is like this:

[INFO] Sources are not up-to-date, XJC will be executed.
[INFO] Parsing input schema(s)...
[INFO] Compiling input schema(s)...
[INFO] Writing output to [C:\des\proyecto\SCOPE\workspace\scope-back\target\generated-sources\xjc-norkom].
[INFO] Cleaning package directories.
[INFO] Episode file [C:\des\proyecto\SCOPE\workspace\scope-back\target\generated-sources\xjc-norkom\META-INF\sun-jaxb.episode] was augmented with if-exists="true" attributes.
[DEBUG] Refreshing the generated directory [C:\des\proyecto\SCOPE\workspace\scope-back\target\generated-sources\xjc-norkom].
[INFO] Finished execution.

I attach the wsdl. 
[wsdl.txt](https://github.com/highsource/maven-jaxb2-plugin/files/2023307/wsdl.txt)

Thanks in advance

**Comment by highsource** [comment]
There's actually nothing to generate.
