### ISSUE TITLE
setting forceRegeneration to false will skip creating files that are in a different execution block

### ISSUE THREAD

**Issue by Kjames5269** [highsource/maven-jaxb2-plugin#161]
If `forceRegeneration` is not set, code generation will be skipped on all executions that come after the first if they are in the same target directory.

For example, in the pom below `wfs-capabilties-generate` will not be generated.
The logs display the following message even though `wfs-capabilties-generate` is out of date. 
```
[INFO] Latest timestamp of the source resources is [2018-11-07 10:14:53.000], earliest timestamp of the target resources is [2018-11-07 10:14:59.000].
[INFO] Sources are up-to-date, XJC will be skipped.
```

Example Pom:
```
<executions>
    <execution>
        <id>wfs-basic-generate</id>
        <goals>
            <goal>generate</goal>
        </goals>
        <configuration>
            <extension>true</extension>
            <schemaDirectory>src/main/resources</schemaDirectory>
            <schemaIncludes>
                <include>wfs/1.0.0/WFS-basic.xsd</include>
            </schemaIncludes>
            <bindingIncludes>
                <include>bindings/wfs-basic-binding.xjb</include>
            </bindingIncludes>
            <args>
                <arg>-Xannotate</arg>
                <arg>-Xvisitor</arg>
                <arg>-Xvisitor-package:ogc.schema.opengis</arg>
            </args>
            <plugins>
                <plugin>
                    <groupId>org.jvnet.jaxb2_commons</groupId>
                    <artifactId>jaxb2-basics-annotate</artifactId>
                    <version>${jaxb2.annotate.version}</version>
                </plugin>
                <plugin>
                    <groupId>com.massfords</groupId>
                    <artifactId>jaxb-visitor</artifactId>
                    <version>${jaxb.visitor.version}</version>
                </plugin>
            </plugins>
        </configuration>
    </execution>
    <execution>
        <id>wfs-capabilties-generate</id>
        <goals>
            <goal>generate</goal>
        </goals>
        <configuration>
            <extension>true</extension>
            <schemaDirectory>src/main/resources</schemaDirectory>
            <schemaIncludes>
                <include>wfs/1.0.0/WFS-capabilities.xsd</include>
            </schemaIncludes>
            <bindingIncludes>
                <include>bindings/wfs-capabilities-binding.xjb</include>
            </bindingIncludes>
        </configuration>
    </execution>
</executions>
```

**Comment by Kjames5269** [comment]
I put together a solution to fix this problem but I'm unsure if this is the best solution. The main idea behind this was if there are multiple executions pointing to the same target directory, after the first one gets executed, [createProducesURIs](https://github.com/highsource/maven-jaxb2-plugin/blob/master/plugin-core/src/main/java/org/jvnet/jaxb2/maven2/RawXJC2Mojo.java#L756) will pick up on those newly created files. Because of how that is used here in [isUpToDate()](https://github.com/highsource/maven-jaxb2-plugin/blob/master/plugin-core/src/main/java/org/jvnet/jaxb2/maven2/RawXJC2Mojo.java#L1001), it will always return true.

**Comment by highsource** [comment]
Please see:

https://github.com/highsource/maven-jaxb2-plugin/wiki/Use-Separate-Target-Directories-for-Separate-Executions

This is known behaviour and the fix is simple: configure separate target directories for separate executions.

I've taken a look at your solution. It involves passing data between executions using a static field. This does not really look safe to me, sorry.

**Comment by Kjames5269** [comment]
No worries, I'll look into the work around. 
Thanks for the quick reply.
