### ISSUE TITLE
Question: Compatibility between version 0.9.1 and 0.13.3

### ISSUE THREAD

**Issue by oilid** [highsource/maven-jaxb2-plugin#162]
Hey,

are the versions 0.9.1 and 0.13.3 compatible? We are using semantic versioning and have to decide if our project should get a new major or minor version number when I upgrade the version of the maven-jaxb2-plugin.

Thanks for a short answer.

Kind regards,
Oilid

**Comment by highsource** [comment]
Please check [Releases](https://github.com/highsource/maven-jaxb2-plugin/releases). Backwards compatibility is normally documenten in every release.

There were many releases between 0.9.1 and 0.13.3. Including JAXB version changes and so on. It is a little but hard to say if it's compatible or not.
I think in most cases you'll get almost the same code generated - and this is what counts for semver. So to play absolutely safe, I'd generate the code with 0.9.1 and 0.13.3 and then diff the generated code. If there are no significant differences (quite probable), there will be no reasons to bump the major.

Hope this helps.

**Comment by oilid** [comment]
I already checked the releases. I thought you are not using semver because in release 0.14 you wrote:

> The plugin must now be built on JDK 9

So this breaks the compatibility between 0.13.3 and 0.14 for me.

Or I'm wrong?

**Comment by highsource** [comment]
The plugin can only be build on Java 9+ but works on Java 8 as well. Don't have Java 7 to test at the moment.

**Comment by oilid** [comment]
So as I told you, you are not using semvar... A version 0.14 has to compatible with 0.13 according to the definition of semvar... But isn't if java6 isn't supported anymore :-/

**Comment by matejsp** [comment]
Semantic versioning is talking about API (https://semver.org/) and not the environment that it runs on. Java 6 is dead and unsupported. Event IBM with the longest support cycle stopped supporting it two month ago (after 10 years).

Besides from SemVer:
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

**Comment by highsource** [comment]
> So as I told you, you are not using semvar... A version 0.14 has to compatible with 0.13 according to the definition of semvar... But isn't if java6 isn't supported anymore :-/

I have not stated I'm using semver. It's more like "shifted" semver.
* My "major" stays `0` as long as I don't feel the plugin is finalized. At least Maven site must be published.
* My "minor" is basically semver "major".
* My "patch" is basically semver "minor".

The project is pretty old, initiated more than 12 years ago. I'd argue it was long before semver was established in the community.
