### ISSUE TITLE
no code generated

### ISSUE THREAD

**Issue by jgarbora** [highsource/maven-jaxb2-plugin#163]
this is my pom ... nothing is generated ... the only error that  I get is: 

[ERROR] Could not retrieve the last modification timestamp for the URI [https://www.clearing.com.uy/WSExperto/WSExperto.WSDL] from the HTTP URL connection. The [Last-Modified] header was probably not set correctly.

`

	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.7.RELEASE</version>
		<relativePath/>
		
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>1.8</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web-services</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>

			<plugin>
				<groupId>org.jvnet.jaxb2.maven2</groupId>
				<artifactId>maven-jaxb2-plugin</artifactId>
				<version>0.13.1</version>
				<executions>
					<execution>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<debug>true</debug>
					<cleanPackageDirectories>true</cleanPackageDirectories>
					<schemaLanguage>WSDL</schemaLanguage>
					<generatePackage>uy.com.clearing</generatePackage>
					<generateDirectory>${project.basedir}/src/main/java</generateDirectory>
					<schemas>
						<schema>
							<url>https://www.clearing.com.uy/WSExperto/WSExperto.WSDL</url>
							
						</schema>
					</schemas>
				</configuration>
			</plugin>
			
		</plugins>
	</build>
</project>`

**Comment by highsource** [comment]
Your [WSDL](https://www.clearing.com.uy/WSExperto/WSExperto.WSDL) does not seem to contain any complex types, so there's nothing for XJC to generate.

You may consider CXF if you interested in generating a WS client.

**Comment by jgarbora** [comment]
I see ... 
this fellows are using RPC .... so I need to go back in time and use Axis 1.4 ... 
thank you @highsource
