### ISSUE TITLE
Preserve element Name in XML when generating Java Objects

### ISSUE THREAD

**Issue by naveenkumaran** [highsource/maven-jaxb2-plugin#164]
The compiler changes the element name representation to camel case when generating java objects. 
For example in my WSDL I have element names such as HelloWorld or HELLO the generated Java property is helloWorld and hello. How do I preserve the element names when generating the Java objects.

**Comment by naveenkumaran** [comment]
Any updates?

**Comment by highsource** [comment]
It works as JAXB is designed. If you want to customize generated names, use one of the options available in binding files.

Changing JAXB naming convention/strategy is not in scope of this plugin.

This will not be implemented.
