### ISSUE TITLE
Plugin leaks classloaders when using in-process strategy

### ISSUE THREAD

**Issue by marcphilipp** [highsource/maven-jaxb2-plugin#168]
When scanning for bindings in dependencies, the plugin creates a `URLClassLoader` that is never closed:

https://github.com/highsource/maven-jaxb2-plugin/blob/3c15b7ee35940859ab75e503ea1bbab89400b9fc/plugin-core/src/main/java/org/jvnet/jaxb2/maven2/RawXJC2Mojo.java#L810

As a result, the underlying JARs in that classloader remain open and cannot be deleted. Also, their content can be stale when opened using `java.util.ZipFile`.

This is a problem when running Maven integration tests using [Embedded3xLauncher](https://github.com/takari/takari-plugin-testing-project/blob/master/takari-plugin-testing/src/main/java/io/takari/maven/testing/executor/Embedded3xLauncher.java). We are developing a Maven extension and want to make sure it works well with this plugin. This classloader leak means we have to use a forking launcher instead, which slows down our tests considerably.

**Comment by highsource** [comment]
I wonder how one would safely close the class loader.

**Comment by marcphilipp** [comment]
I may be missing sth. but since the method only returns `URIs`, I don't see why it would not be safe to close it.

**Comment by marcphilipp** [comment]
@highsource I've submitted a PR to fix this in #169.
