### ISSUE TITLE
Binding by namespace not working

### ISSUE THREAD

**Issue by deslauriersp** [highsource/maven-jaxb2-plugin#171]
I am trying to map a package name to a namespace

As per the doc : https://github.com/highsource/maven-jaxb2-plugin/wiki/Configure-Target-Packages-in-Binding-Files

```
	<jaxb:bindings xmlns:tns="http://www.myexample.com/my-service/request" scd="x-schema::tns">
		<jaxb:schemaBindings >
			<jaxb:package name="com.request" />
		</jaxb:schemaBindings>
	</jaxb:bindings>
```

It seems to be ignored. 

see full sample : https://github.com/deslauriersp/jaxb-bindings-not-working

posted on stackoverflow.com as well
https://stackoverflow.com/questions/55657528/jaxb-bindings-package-for-namespace-scd-not-working

**Comment by highsource** [comment]
Does it work with pure XJC? From the command line?

**Comment by deslauriersp** [comment]
It took me a while to get XJC working from the command line
Thank to the plugins I haven't done that in decades :)

You guessed right -> it doesn't work with xjc

The problem seems to with the "-wsdl" option
When trying with both XSD and binding files it works

Thank

Phil

**Comment by highsource** [comment]
So I guess I can't do much here.
