### ISSUE TITLE
Can it generate XSD from Java Beans?

### ISSUE THREAD

**Issue by amihaiemil** [highsource/maven-jaxb2-plugin#174]
As I see, this plugin is used to generate Java models out of existing XSD files. Can it also work the other way around, generate schemas from Java classes annotated with JAXB?

**Comment by highsource** [comment]
No, this plugin only generates Java classes from schemas.
See the Codehaus `jaxb2-maven-plugin` (https://www.mojohaus.org/jaxb2-maven-plugin/Documentation/v2.2/), it has a `schemagen` goal.

**Comment by Lonzak** [comment]
> No, this plugin only generates Java classes from schemas. See the Codehaus `jaxb2-maven-plugin` (https://www.mojohaus.org/jaxb2-maven-plugin/Documentation/v2.2/), it has a `schemagen` goal.

This is unfortunate... because the referenced plugin is not jakarta compatible...

**Comment by mattrpav** [comment]
@Lonzak generating XSD from existing classes is often referred to as 'bottom-up' generation. The Apache XBean project has a way to do it using their custom tag (which is added to comments so it is only a build time dependency), and I know there have been other tools that have done it in the past.
