### ISSUE TITLE
Proposal for GWT wrapper

### ISSUE THREAD

**Issue by gitgabrio** [highsource/maven-jaxb2-plugin#177]
Good day,
my name is Gabriele Cardosi (https://github.com/gitgabrio) and I'm working at RedHat. For one of our GWT project we need to implement XML marshalling client-side. My idea is to "wrap" your jsonix library and call it using GWT JSInterop. My preliminary experiment with simple PO project worked, but now I need a way to automatically generate the required java classes. Those classes should only declare getter/setter (as in the JAXB-generated ones), but without any annotation (beside the JsInterop ones) and with empty bodies (e.g. `public final native String getName();` ).
I've worked in the past with both JAXB and other Maven plugin, so it crossed my mind to extend this plugin with a "GWT JsInterop" goal or something similar  to generate (on demand) the above classes: if I implement it, would you agree to add this functionality ?
Best Regards
Gabriele

**Comment by highsource** [comment]
Hi,

I think this is more suitable for https://github.com/highsource/jsonix-schema-compiler and I suggest to continue the discussion there. (Please file a new issue there.)

I understand the idea and I think this is a useful thing to implement. Actually, XJC plugins even have a nice mechanism for this very use case. You can implement and set an instance of `com.sun.tools.xjc.generator.bean.field.FieldRendererFactory` which would render your Java classes just as you want them. So, basically you'd simply extend `org.hisrc.jsonix.xjc.plugin.JsonixPlugin` and set your `FieldRendererFactory` via `Options.setFieldRendererFactory(...)` in `onActivated` there.

The question is, however if this should be part of Jsonix Schema Compiler or not.

I think we'll be better of if this is implemented as a separate project based on Jsonix Schema Compiler for a few reasons, to name a few:

* I don't have any GWT experience, so I'll have hard time maintaining GWT parts afterwards.
* I also don't (and probably will not) have any GWT projects in the forseeable future so no grounds to gain said GWT experience.
* Jsonix Schema Compiler is not the simplest thing as it is, adding GWT generation flavor on top of it will make things even more complicated.

So I think it will be better if you start your own "Jsonix Schema Compiler for GWT" project, based on Jsonix Schema Compiler. I'd be happy to help you get started.

(I'm closing this issue, please open a new one in Jsonix Schema Compiler if you wish to continue the discussion.) 

Best wishes,
Alexey

**Comment by gitgabrio** [comment]
@highsource 
Hi Alexey, 
many thanks for your answer and help! I understand your doubt about maintaining GWT-specific stuff, I'll follow your suggestion.
Best

Gabriele
