### ISSUE TITLE
Unmarshal Exception message mentions optional fields

### ISSUE THREAD

**Issue by Phiroc** [highsource/maven-jaxb2-plugin#185]
Hello,
I am getting the following UnmarshalException in a Java 1.8.0_191 program running on Windows 10, that uses classes generated using the jaxb2 Maven plugin version 2.5.0 :

> JAXB unmarshalling exception; nested exception is javax.xml.bind.UnmarshalException
>  - with linked exception:
> [org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 622; cvc-complex-type.2.4.a : Contenu non valide trouvé à partir de l'élément 'MotifCommande'. L'une des valeurs '{AliasCde, RefExterneCde, DateDepot}' est attendue.]

In English:
`Invalid content found starting with the MotifCommand item. One of the items '{AliasCd, RefExterneCde, DateDepot}' is expected.]`

Strangely enough, the AliasCd and RefExterneCde are optional. Why are they at all mentioned in the exception message?

Furthermore, why does the message state that the content is invalid starting with the MotifCommande tag, which appears to be _after_ the (mandatory) DateDepot tag, in the XSD?

Please find enclosed the XSDs and a sample SOAP request.

[github.zip](https://github.com/highsource/maven-jaxb2-plugin/files/3892755/github.zip)

**Comment by highsource** [comment]
This is a JAXB issue, not related to the `maven-jaxb2-plugin`.

**Comment by Phiroc** [comment]
Hi Alexey,

how do you report a JAXB issue?

Best regards,

Phiroc

----- Mail original -----
De: "Alexey Valikov" <notifications@github.com>
À: "highsource/maven-jaxb2-plugin" <maven-jaxb2-plugin@noreply.github.com>
Cc: "Phiroc" <phiroc@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Mardi 26 Novembre 2019 17:23:44
Objet: Re: [highsource/maven-jaxb2-plugin] Unmarshal Exception message mentions optional fields (#185)



This is a JAXB issue, not related to the maven-jaxb2-plugin .

**Comment by highsource** [comment]
@Phiroc I do not think this is a bug/problem in JAXB/JAXB RI. More probably this is a normal development issue. As in "probably you're doing something wrong".
So on your place I'd first build a MCVE (which you're probably quite close to) and ask on StackOverflow.
