### ISSUE TITLE
Dead or alive?

### ISSUE THREAD

**Issue by petebrew** [highsource/maven-jaxb2-plugin#193]
I'm trying to upgrade code that I inherited that was written for Java 8.  It seems some steps have been made to support Java 11 in the maven-jaxb2-plugin, but things have been quiet for a couple of years now.  Is this plugin plugin dead or alive?  Do I need to look elsewhere?

**Comment by FranklinChen** [comment]
I have a feeling it is dead. I'm trying to figure out how to move on with my old JAXB-using project.

**Comment by soberich** [comment]
> I have a feeling it is dead. I'm trying to figure out how to move on with my old JAXB-using project.

@FranklinChen what are the findings so far?
Any good alternative?

**Comment by FranklinChen** [comment]
https://github.com/mojohaus/jaxb2-maven-plugin is active and now supports JAXB 3 also.

**Comment by mattrpav** [comment]
Please see: https://github.com/highsource/maven-jaxb2-plugin/issues/206
