### ISSUE TITLE
[0.12.0 on JDK 8] required class com.sun.tools.internal.xjc.outline.Aspect missing 

### ISSUE THREAD

**Issue by dukehoops** [highsource/maven-jaxb2-plugin#24]
Attempting to run `generate` using Oracle / OS X JDK 8, getting the error below. Note that the only `Aspect` I was able to find is tools.jar as `com.sun.tools.internal.xjc.outline.Aspect`

ERROR] Failed to execute goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.0:generate (jaxb-YAOfferIngestionService) on project castanealabs-core: Execution jaxb-YAOfferIngestionService of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.0:generate failed: A required class was missing while executing org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.0:generate: com/sun/tools/xjc/outline/Aspect
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/nikita/.m2/repository/org/jvnet/jaxb2/maven2/maven-jaxb2-plugin/0.12.0/maven-jaxb2-plugin-0.12.0.jar
[ERROR] urls[1] = file:/Users/nikita/.m2/repository/org/jvnet/jaxb2/maven2/maven-jaxb2-plugin-core/0.12.0/maven-jaxb2-plugin-core-0.12.0.jar
[ERROR] urls[2] = file:/Users/nikita/.m2/repository/com/sun/org/apache/xml/internal/resolver/20050927/resolver-20050927.jar
[ERROR] urls[3] = file:/Users/nikita/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar
[ERROR] urls[4] = file:/Users/nikita/.m2/repository/junit/junit/4.8.1/junit-4.8.1.jar
[ERROR] urls[5] = file:/Users/nikita/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.15/plexus-utils-1.5.15.jar
[ERROR] urls[6] = file:/Users/nikita/.m2/repository/org/jvnet/jaxb2/maven2/maven-jaxb22-plugin/0.12.0/maven-jaxb22-plugin-0.12.0.jar
[ERROR] urls[7] = file:/Users/nikita/.m2/repository/com/sun/xml/bind/jaxb-core/2.2.11/jaxb-core-2.2.11.jar
[ERROR] urls[8] = file:/Users/nikita/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.11/jaxb-impl-2.2.11.jar
[ERROR] urls[9] = file:/Users/nikita/.m2/repository/com/sun/xml/bind/jaxb-xjc/2.2.11/jaxb-xjc-2.2.11.jar
[ERROR] urls[10] = file:/Users/nikita/.m2/repository/org/apache/maven/plugin-tools/maven-plugin-annotations/3.2/maven-plugin-annotations-3.2.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------: com.sun.tools.xjc.outline.Aspect
[ERROR]

```xml

<dependencies>
 <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
            <version>2.2.11</version>
        </dependency>
</dependencies>
 <build>
        <plugins>
            <!-- generate Java classes from YA web service XSDs using JAXB2 -->
            <plugin>
                <groupId>org.jvnet.jaxb2.maven2</groupId>
                <artifactId>maven-jaxb2-plugin</artifactId>
                <version>0.12.0</version>
                <executions>
                    <execution>
                        <id>jaxb1</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
```

**Comment by highsource** [comment]
Please see this discussion:

https://java.net/projects/jaxb/lists/users/archive/2014-12/message/18

In short, the `Aspect` class was moved to another package. This potentially breaks many plugins. I've let JAXB team know about the problem and they have reverted it in the next version of JAXB RI.

As there's no action required in `maven-jaxb2-plugin`, I'm closing the issue as `won't fix`.

**Comment by dukehoops** [comment]
Thanks, makes sense. Appreciate  the follow up

**Comment by stewbis** [comment]
Hi, This issue still exists when using the plugin on Java 8. I think Java 8 still ships with an older version of the JAXB RI. What is the workaround to enable the plugin to work with Java 8?
Thanks, Stewart

**Comment by highsource** [comment]
@stewbis Can you provide a minimal reproducing project?

**Comment by stewbis** [comment]
@highsource will put together a project to reproduce. Regards, Stewart

**Comment by stewbis** [comment]
@highsource. I locally put together a project and found it was a problem triggered by using the jaxb2-basics plugin. Apologies for re-raising the issue. Regards Stewart

**Comment by highsource** [comment]
No problem. jaxb2-basics should work though, maybe you need to upgrade the version.
