### ISSUE TITLE
Dropping plugin-2.0, plugin-2.1, plugin-2.2

### ISSUE THREAD

**Issue by mattrpav** [highsource/maven-jaxb2-plugin#241]
In preparation for the jakarta migration, we will be dropping support for the JAXB 2.0, 2.1 and 2.2 plugin.

All users are encouraged to upgrade to the plugin-2.3 to use with JDK 8 + JAXB (javax)

**Comment by laurentschoelens** [comment]
Pull request done for this : https://github.com/highsource/maven-jaxb2-plugin/pull/255
