### ISSUE TITLE
Don't be so verbose in "Up-to-date check for source resources"

### ISSUE THREAD

**Issue by highsource** [highsource/maven-jaxb2-plugin#31]

**Comment by Stephan202** [comment]
Also, in version 0.12.3 of the plugin this line contains a typo further down:

> [...] and **taret** resources [...]

**Comment by Stephan202** [comment]
Never mind, I see you already fixed that in #32 :)

**Comment by taavipyry** [comment]
Hey, would 

`        if (getVerbose()) {
            getLog().info(MessageFormat.format("Up-to-date check for source resources [{0}] and target resources [{1}].",
                    dependsURIs, producesURIs));
        }`

fix this issue? I am having log bloat issues with target resource parameter.

**Comment by highsource** [comment]
Or switching to `debug(...)`.

**Comment by taavipyry** [comment]
That would cover it well.
