### ISSUE TITLE
m2e: plugin should be run on configuration

### ISSUE THREAD

**Issue by victornoel** [highsource/maven-jaxb2-plugin#33]
Hi,

Because the plugin adds a source directory, the lifecycle configuration should be run on configuration for m2e to pick-up the extra source folder.

The change would be trivial in lifecycle-mapping-metadata.xml

Note that it seems that the default plugin maven-jaxb2-plugin is ok, but the jaxb20, jaxb21 and jaxb22 are wrong.

**Comment by highsource** [comment]
Thank you for the report!

I'll make `lifecycle-mapping-metadata.xml` identical in all the four cases, as in the `maven-jaxb2-plugin`.

**Comment by highsource** [comment]
Is fixed now, will be released in `0.12.4`. Thank your the report!
