### ISSUE TITLE
What is the difference between this plugin and the codehaus one?

### ISSUE THREAD

**Issue by alrighttheresham** [highsource/maven-jaxb2-plugin#35]
Sorry not really an issue, but since both are being actively developed it would be good to get a view between each.  Possibly add the answer to your FAQ?

**Comment by highsource** [comment]
A good question. I'll add it to the FAQ later on.

In short:

Cons:
* This plugin does not provide a [`schemagen`](http://mojo.codehaus.org/jaxb2-maven-plugin/schemagen-mojo.html) goal.
* There's no [Maven-generated website](http://mojo.codehaus.org/jaxb2-maven-plugin/) (yet).

Pros:
* Config-level support for episodes and XJC plugins.
* Maven integration.
  * You can compile schemas [directly from Maven artifacts](https://github.com/highsource/maven-jaxb2-plugin/wiki/Referencing-Resources-in-Maven-Artifacts).
  * Use [catalogs](https://github.com/highsource/maven-jaxb2-plugin/wiki/Using-Catalogs#using-catalogs) to resolve schemas to resources inside Maven artifacts.
  * Use Mavern artifacts as [episodes](https://github.com/highsource/maven-jaxb2-plugin/wiki/Using-Episodes) or [XJC plugins](http://mojo.codehaus.org/jaxb2-maven-plugin/).
* [JAXB 2.0, 2.1 and 2.2 variants](https://github.com/highsource/maven-jaxb2-plugin/wiki/Using-a-Specific-JAXB-Version).
* Provides workarounds for some of the XJC bugs ([example](https://github.com/highsource/maven-jaxb2-plugin/releases/tag/0.10.0)).
* A few more minor (but makes-your-life-easier) fixes.

I did not manage to find a single reasonable feature of [`jaxb2-maven-plugin:xjc`](http://mojo.codehaus.org/jaxb2-maven-plugin/xjc-mojo.html) which `maven-jaxb2-plugin` wouldn't implement in one or the other way. If you'll find any, let me know.

It is a somewhat hard to be unbiased on the question but I hope I was factual.

Would you by the way mind asking the same question the [CodeHaus guys](https://jira.codehaus.org/browse/MJAXB)? I'd like to hear what they say.

**Comment by alrighttheresham** [comment]
Thanks same question raised at codehaus. https://jira.codehaus.org/browse/MJAXB-116 <https://jira.codehaus.org/browse/MJAXB-116> 

Regards,
Damian.

**Comment by Stephan202** [comment]
Thanks for this; I recently wondered about the difference as well. I voted for your question @ JIRA ;).

**Comment by highsource** [comment]
Hi Guys, thanks for both taking the time to reply, especially given the awkwardness of the question. It is very encouraging that you are willing to look at a collaboration in the future, this makes perfect sense particularly given the extensive use of these plugins in production software worldwide.
With regards to my original question, which is driven by us finding both plugins used in different multi-module projects within our company (therefore validating that both are fit for our purpose), I will proceed with my normal criteria for open source selection.
1. Is the license commercially friendly
2. Is the software currently maintained
3. Does the software's dependencies use the latest stable releases from the third parties they source
4. Does the project have comprehensive unit tests and coverage reports
5. Does the project use static code analysis as part of the build, for e.g. pmd, checkstyle, findbugs, etc. 
6. Does the project have an active forum
Again thanks, I really appreciate Lennart and Alexey you taking the time to answer my question. 
Damian.

****

> 1. Is the license commercially friendly

Yes, 2-clause BSD: https://github.com/highsource/maven-jaxb2-plugin/blob/master/LICENSE.

> 2. Is the software currently maintained

Yes.

> 3. Does the software's dependencies use the latest stable releases from the third parties they source

Mostly yes with a few exceptions ("provided" Maven artifacts). The JAXB libraries are the latest, but versions for older JAXB (2.0.x and 2.1.x) are also provided.

> 4. Does the project have comprehensive unit tests and coverage reports

Yes: https://github.com/highsource/maven-jaxb2-plugin/tree/master/tests

Compile tools are different from "normal" libraries so tests suit is also somewhat different. It is a (huge) set of test projects.

> 5. Does the project use static code analysis as part of the build, for e.g. pmd, checkstyle, findbugs, etc.

No.

> 6. Does the project have an active forum

Yes: http://stackoverflow.com/questions/tagged/maven-jaxb2-plugin

**Comment by alrighttheresham** [comment]
Thankyou Alexey you've saved me the time in looking this up.  Again very prompt / great support.  

Damian.

**Comment by highsource** [comment]
No problem, glad you've asked.
I've contacted Lennart about collaboration.

**Comment by highsource** [comment]
The question seems to be answered so I'll close the issue.
