### ISSUE TITLE
Allow to specify the order of xsd files

### ISSUE THREAD

**Issue by AlexanderWillner** [highsource/maven-jaxb2-plugin#39]
I think I just had the same issue as described at http://stackoverflow.com/questions/27026057/maven-jaxb2-plugin-how-to-accomplish-this-xjc-command-line-in-the-pom-xml
Compilation works fine on my machine (OS X), after renaming the XSD files to enforce an alphabetical order. On travis on the other hand it doesn't work.
A concrete example is shown here: https://travis-ci.org/open-multinet/playground-rspecs-ontology/builds/47955608

**Comment by highsource** [comment]
There's a solution here:

http://stackoverflow.com/questions/27026057/maven-jaxb2-plugin-how-to-accomplish-this-xjc-command-line-in-the-pom-xml

Using multiple `schemas/schema`. Does this work for you?

**Comment by AlexanderWillner** [comment]
Thanks for the answer. What actually helped was to add <nv>true</nv> and not (only)  <strict>false</strict>. Now I even don't need to rename the files to enforce an order (on my machine). See https://github.com/open-multinet/playground-rspecs-ontology/commit/cc5bb6fc7ba9ae5f6810f8e0fc3a6df3ce0abede

**Comment by highsource** [comment]
I wondered about this as I don't have the `nv` setting at all. And then it appears that you're using `jaxb2-maven-plugin`:

https://github.com/open-multinet/playground-rspecs-ontology/blob/master/pom.xml#L108

This project develops *the other* plugin, namely `maven-jaxb2-plugin`.
You're on the wrong project here. :)

**Comment by AlexanderWillner** [comment]
ups
