### ISSUE TITLE
Taking care of the "SCD "x-schema::tns" didnt match any schema component" error

### ISSUE THREAD

**Issue by victornoel** [highsource/maven-jaxb2-plugin#41]
Hi,

I faced the error "SCD "x-schema::tns" didnt match any schema component" that happens when an episode declares namespaces not used in the xsd of the project using that episode.

This is very annoying and I found out that it is an old bug never fixed: http://metro.1045641.n5.nabble.com/Re-JAXB-2-1-unused-namespaces-in-episode-file-raise-an-exception-td1054910.html

In this thread, they propose as a workaround to add an extra attribute in the generated episode file to the scd elements in order to have them getting ignored later.

Do you think there could be anyway that such a workaround is enforced by maven-jaxb2-plugin? With some kind of post-processing of the generated episode file for example.

Thank you

**Comment by highsource** [comment]
Hi,

I also suffer from this. :( Very annoying. I have to include unrelated schemas just because XJC does not work otherwise.

I would love to fix it but not sure if I can. I'll take a look. Through patching XJC - yes, sure, but probably not through "normal" means.

What I am considering for a while now is starting a patch project for XJC:

https://github.com/highsource/exjc

Where we could apply patches to XJC that Oracle won't apply.
This issue could also be placed there.

Best wishes,
Alexey

**Comment by victornoel** [comment]
Hi,

As a hack/workaround, I was thinking about something like applying a some kind a stupid transformation to the episode file after it is generated by xjc so that every bindings with scd value "x-schema::tns" has the supplementary attribute "if-exists" added.

Of course it is not a long term solution…

Do you think you could quickly document how you workaround this problem (you said "I have to include unrelated schemas") in your projects?

Thank you very much!

**Comment by highsource** [comment]
Does this "if-exists" thing work already? Then we could approach it from two sides. One is to fix the episodes plugin in XJC. And the other one is - really - to do a prior XSLT transform. A bit weird but will fix it. XSLT could be applied "transparenty" via the resource resolver.

**Comment by victornoel** [comment]
Yes, I checked the source code of xjc and it actually checks for that if-exists hack to not complain about unused namespace.
That's what the linked newsgroup discussion was about.

I was playing ab it and made this XSLT, but it's the first time I'm playing with that so maybe it can be improved:
```xml
<?xml version="1.0" encoding="UTF-8"?>

<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:jaxp="http://java.sun.com/xml/ns/jaxb"
   version="1.0">

    <!-- this template is applied by default to all nodes and attributes -->
   <xsl:template match="@*|node()">
        <!-- just copy all my attributes and child nodes, except if there's a better template for some of them -->
      <xsl:copy>
         <xsl:apply-templates select="@*|node()" />
      </xsl:copy>
   </xsl:template>

   <xsl:template match="jaxp:bindings[@scd='x-schema::tns']">
      <xsl:copy>
         <xsl:attribute name="if-exists">true</xsl:attribute>
         <xsl:apply-templates select="@*|node()" />
      </xsl:copy>
   </xsl:template>

</xsl:stylesheet>
```

I will let you handle how to apply the transformation, because I did some tests with your code, but I am really an amateur with these libraries :)

**Comment by highsource** [comment]
Yes, it's not quite easy to get in.

Let's talk about the config. My suggestion would be to have some config switch to turn the fix on as it might break in the first versions. And then flip it to default in the next major version, what do you think?
Something like `allowUnusedSchemaBindings`?

Could you please also check if there's a JAXB issue for that (in their JIRA) and file one if not? That would be great help.

I'll integrate XSLT in the next version.

**Comment by victornoel** [comment]
I agree for the switch yes, maybe allowUnusedSchemaBindingsInEpisodes so that it is clear that it is for episodes… but well, there is always the documentation :)

So if I understood well you will apply the XSLT before loading the episode file in a project that uses the episode? I was thinking of generating a fixed episode file… but your solution is safer I guess :)

As for an open issue, there is this one: https://java.net/jira/browse/JAXB-335

Thank you!

**Comment by highsource** [comment]
I was thinking both. Generating a fixed episode is one. But we'll also need to deal with "unfixed" episodes.
I think there's a way to pur a resource resolver between the binding file and XJC. Then the transformation could be applied transparently in the runtime. binding files are not big so that won't be a big deal. A drawback is that it introduces some indirection so in case of problems it will be harder to diagnose.

But I think the advantages are greater.

Thank you for the link and the report. What the issue, you'll get notified when it is implemented. Can't promise a date though.

**Comment by victornoel** [comment]
My pleasure, thanks to you for the reactivity :)

2015-02-06 16:53 GMT+01:00 Alexey Valikov <notifications@github.com>:

**Comment by Swierkowski** [comment]
This discussion is 6 months old. What about the implementation?

**Comment by highsource** [comment]
The project is open for pull requests.

**Comment by highsource** [comment]
Ok, I think I've got this. The new option is called `addIfExistsToEpisodeSchemaBindings` and it is `true` by default. Transformation via intermediate DOM to spare the temp file.

See:
* https://github.com/highsource/maven-jaxb2-plugin/wiki/Using-Episodes#adding-if-existstrue

@victornoel @andreptb Could you please check if it works for you, thanks.

**Comment by victornoel** [comment]
Yep, version 0.13.0 seems to work as desired for me!
Thanks @andreptb and @highsource
