### ISSUE TITLE
Ignore few classes while generating sources

### ISSUE THREAD

**Issue by mshafieluru** [highsource/maven-jaxb2-plugin#45]
Hi 

I have a common xsd file to be used across my webserive wsdl files. i do not want to generate all the classes in along with wsimport of wsdl file in each webservice. Instead i created a single jar file of xsd and want to use it in all projects.

I want to ignore the classes of common xsd file while using wsimport into target/generated-sources folder.

please suggest solution

**Comment by highsource** [comment]
Hi,

check this page in Wiki:

https://github.com/highsource/maven-jaxb2-plugin/wiki/Modular-Schema-Compilation

And this test project:

https://github.com/highsource/maven-jaxb2-plugin/tree/master/tests/MAVEN_JAXB2_PLUGIN-82

What you need is [episodes](https://github.com/highsource/maven-jaxb2-plugin/wiki/Using-Episodes).

Best wishes,
Alexey

**Comment by highsource** [comment]
Is it solved for you now?

**Comment by mshafieluru** [comment]
I will try out the solution provided. I hope this will work.

**Comment by mshafieluru** [comment]
Thanks alot
