### ISSUE TITLE
Configuration option for additional JVM arguments

### ISSUE THREAD

**Issue by mkotelba** [highsource/maven-jaxb2-plugin#48]
It would be lovely to be able to specify additional JVM arguments.

The XJC executable doesn't appear to directly support such a thing, but I've seen it done before in similar Maven plugins (ex. [cxf-codegen-plugin](http://cxf.apache.org/docs/maven-cxf-codegen-plugin-wsdl-to-java.html)).

**Comment by highsource** [comment]
`maven-jaxb2-plugin` executes XJC in the same process, it does not start a separate VM This makes a few nice features like [using Maven artifacts](https://github.com/highsource/maven-jaxb2-plugin/wiki/Referencing-Resources-in-Maven-Artifacts) possible.

So in the current architecture there's no separate VM, therefore JVM arguments can't be set.

Why do you need this feature? For what purpose?

**Comment by mkotelba** [comment]
Aside from selectively giving the XJC JVM more compute resources (minor), I've been seeing SLF4J's "no StaticBinder"-style of errors from the plugin during builds.

I've got SLF4J's + Logback's dependencies in the overall project compile scope (none of them explicitly set as dependencies of the maven-jaxb2-plugin itself). I've seen similar behavior with the CXF Codegen plugin, but was able to solve it by supplying that plugin with Logback's dependencies + it's XJC JVM with the system properties it wanted to be able to configure Logback at runtime.

If the underlying problem doesn't turn out to be SLF4J/Logback/Maven being wonky, and the only possible fix is to make SLF4J/Logback happy, another possible solution would perhaps be to add a configuration property for adding extra classpath paths to the plugin's internal classpath (looking at the code, it already does this to make things like JAXB extensions + schemas in Maven dependencies work); it would then be possible to just stick /logback.xml file in the classpath.

**Comment by highsource** [comment]
> Aside from selectively giving the XJC JVM more compute resources (minor)...

This is done via Maven options then.

> I've been seeing SLF4J's "no StaticBinder"-style of errors from the plugin during builds.

We could address this as an extra issue. I did few things for the tighter SLF4J integration, but maybe something's not yet working well. Please consider committing a minimal reproducing project, I'll hanlde it then.

If there's anything else you'd like to hanlde via VM params, please file specific issues. As I noted before, in the existing architecture there's no separate VMs so this request can't be implemented. You may want to consider other Maven JAXB plugins (CXF or the CodeHaus one). They lack some of this plugin's features. But these are exactly the features which depend on running XJC in the same VM.

I'm closing this with won't fix, hope for your understanding.

**Comment by mkotelba** [comment]
Fair enough.

I've managed to come across a Maven dependency that appears to be tremendously relevant: http://search.maven.org/#search|ga|1|a%3A%22maven-jaxb2-plugin-slf4j-binding%22

Forgive me if I'm misunderstanding the relationship between the (deprecated? abandoned?) jvnet JAXB stuff and the highsource stuff, and you have no more of an idea than anyone else :)

**Comment by highsource** [comment]
I had my projects previously hosted in java.net (therefore the `jvnet.org`-based `groupId`s). Most of the projects are already moved to github.

But there are also other projects with `jvnet.org` groupIds which are not mine.

See this issue on the artifact you're referring to:

* https://github.com/highsource/maven-jaxb2-plugin/issues/29

As for your `crigtt` project, would you please file an describe the specific issue you're seeing? I have rather limited resources so I do not always have time to check out/build/test third-party projects. I'd need an issue - and if it is not a trivial one - a *minimal* reproducing project.  
I hope for your understanding.
