### ISSUE TITLE
What is possible using bindings files?

### ISSUE THREAD

**Issue by phnmnm** [highsource/maven-jaxb2-plugin#51]
Hi,

I didnt find another way to contact you. This is why I ask you this question here.

I am trying to generate Java-stubs from a DTD file. The problem is that i get ugly
List<Object> studentOrTeacherOrProfOr... class members.

I didnt find a way using the mojo... plugin so I tried your plugin, because I saw the binding files for DTD.

In your hibernate DTD example you rename the "class" DTD element to a "Clazz" Java class.

Is it only possible to rename things at generation time?

If there is a way to split the above example into 3 member variables it would be great.

Hope you can help me!

best regards

**Comment by phnmnm** [comment]
Didnt find a way to mark it as a question.. :(

**Comment by highsource** [comment]
Check the simplify plugin:

https://github.com/highsource/jaxb2-basics/wiki/JAXB2-Simplify-Plugin

I think it should do exactly what you want.

**Comment by phnmnm** [comment]
Thanks for the fast answer. It is exactly what I want to do. But I am completely confused now?

Right now I have a xxxx.xjb with:

<?xml version="1.0"?>
<xml-java-binding-schema>
        ...
	<element name="property" type="class">
		...
	</element>
        ....
</xml-java-binding-schema>

The simplify plugin needs a *.xjb file with something like:

<jaxb:bindings
    xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:simplify="http://jaxb2-commons.dev.java.net/basic/simplify"
    jaxb:extensionBindingPrefixes="simplify">
    ...
    <jaxb:bindings node="xs:complexType[@name='typeWithElementsProperty']/xs:choice">
        <simplify:as-element-property/>
    </jaxb:bindings>
    ...
</jaxb:bindings>

I only have a DTD file which means no types. How can I tell the binding which element it should take?! Or do I have to just set the '@name'?

**Comment by phnmnm** [comment]
Another problem is where do I set the location of the bindings file?

    <plugin>
        <groupId>org.jvnet.jaxb2.maven2</groupId>
        <artifactId>maven-jaxb2-plugin</artifactId>
        <version>0.12.3</version>
        <executions>
          <execution>
            <id>v213</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <generateDirectory>src/main/gen_v213</generateDirectory>
              <schemas>
                <schema>
                  <fileset>
                    <directory>src/main/resources/dtd/v213</directory>
                    <includes>
                      <include>TradeXML.dtd</include>
                    </includes>
                  </fileset>
                </schema>
              </schemas>
              <schemaLanguage>dtd</schemaLanguage>
              
            </configuration>
          </execution>
          <execution>
            <id>v123</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <generateDirectory>src/main/gen_v123</generateDirectory>
              <schemas>
                <schema>
                  <fileset>
                    <directory>src/main/resources/dtd/v123</directory>
                    <includes>
                      <include>TradeXML.dtd</include>
                    </includes>
                  </fileset>
                </schema>
              </schemas>
              <schemaLanguage>dtd</schemaLanguage>
              
            </configuration>
          </execution>
        </executions>
      </plugin>

At every place I tried to add the bindingIncudes the <execution> tag says: Cannot find getter/setter or field "bindingIncludes" ...

**Comment by phnmnm** [comment]
The maven problem is no more... 

    <plugin>
        <groupId>org.jvnet.jaxb2.maven2</groupId>
        <artifactId>maven-jaxb2-plugin</artifactId>
        <version>0.12.3</version>
        <executions>
          <execution>
            <id>v213</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <generateDirectory>src/main/gen_v213</generateDirectory>
              <schemas>
                <schema>
                  <fileset>
                    <directory>src/main/resources/dtd/v213</directory>
                    <includes>
                      <include>TradeXML.dtd</include>
                    </includes>
                  </fileset>
                </schema>
              </schemas>
              <bindings>
                <binding>
                  <fileset>
                    <directory>src/main/resources/xjb</directory>
                    <includes>
                      <include>v213.xjb</include>
                    </includes>
                  </fileset>
                </binding>
              </bindings>
              <schemaLanguage>dtd</schemaLanguage>
            </configuration>
          </execution>
          <execution>
            <id>v123</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <bindings>
                <binding>
                  <fileset>
                    <directory>src/main/resources/xjb</directory>
                    <includes>
                      <include>v123.xjb</include>
                    </includes>
                  </fileset>
                </binding>
              </bindings>
              <generateDirectory>src/main/gen_v123</generateDirectory>
              <schemas>
                <schema>
                  <fileset>
                    <directory>src/main/resources/dtd/v123</directory>
                    <includes>
                      <include>TradeXML.dtd</include>
                    </includes>
                  </fileset>
                </schema>
              </schemas>
              <schemaLanguage>dtd</schemaLanguage>
              <extension>true</extension>
              <args>
                <arg>-Xsimplify</arg>
              </args>
              <plugins>
                <plugin>
                  <groupId>org.jvnet.jaxb2_commons</groupId>
                  <artifactId>jaxb2-basics</artifactId>
                  <version>0.9.4</version>
                </plugin>
              </plugins>

            </configuration>
          </execution>
        </executions>
      </plugin>

**Comment by highsource** [comment]
Ah, you've got DTD... I'm afraid JAXB does not process customizations on DTDs. Or at least I don't know the syntax.

Theoretically the simplify plugin could be extended to support other ways of customization - or "simplify everything automatically".

But I would really recommend to consider converting DTD to XSD. You'll get less trouble at the end.

**Comment by phnmnm** [comment]
Unfortunately thats no option...

I converted my dtd in xsd with trang. But generating java stubs from this xsd gives me resolution errors because there are several Entities with the same name...
