### ISSUE TITLE
Missing method classes from wsdl

### ISSUE THREAD

**Issue by Kernle32DLL** [highsource/maven-jaxb2-plugin#53]
Hello,

I tried to compile a wsdl file I got today. All the types for use in the service calls are generated correctly, as well as the responses. But the classes for the actual calls to the service are not generated.

Here is the wsdl file: https://dosicon.helmholtz-muenchen.de/gksst/V12x/demo/GkSstServer?wsdl

I'm working with the Spring WS Tutorial: https://spring.io/guides/gs/consuming-web-service/

I have no Idea why this is the case. Is this a problem with this project, or is the wsdl wrong?

What I could tell, comparing the weather wsdl from the tutorial and mine, is that the method calls in my wsdl are not defined as types. Just the accompanying message and operations.

When using SoapUI, the method calls are constructed correctly. So I presume a problem with the generation in this project.

**Comment by highsource** [comment]
Have you actually tried the Spring WS Tutorial? Are classes for the actual calls to the service generated in the tutorial?

I think XJC only generates classes which are derived from schemas referenced in the WSDL, it does not generate actual service endpoint, you'll need `wsimport` or something like that for this.

**Comment by Kernle32DLL** [comment]
@highsource Yes, in the Spring WS Tutorial the calls to the service are generated. Currently, we put the service calls into the types section by hand (which is quite tedious and error prone). But it works.

Like I said - the question remains which side is in error here. I will look into wsimport tho.

**Comment by victornoel** [comment]
Are you sure you can't create the object with the ObjectFactory?

I have done the same tutorial lately and used maven-jaxb2-plugin to generate the classes from the WSDL and the ObjectFactory gives me methods to generate the needed JAXBElement to do the calls: this is because jaxb generates types, not the elements, and even though I can't access your wsdl anymore, I would suppose the classes you are looking for are for declared elements and not types.

It is not related to maven-jaxb2-plugin per-se but to the way jaxb is meant to work.

**Comment by Kernle32DLL** [comment]
Well, the WSDL is still accessible. The only browser I know to make problems is Firefox due to the weak encryption. Use a different Browser.

And @victornoel - you are right. The method calls are not in the types section (while in the Spring WS tutorial the methods are). But like I said - I can't determinate if this is correct or not.

Dunno about the ObjectFactory, but since the classes "are just not there", I don expect a difference.

**Comment by victornoel** [comment]
@Kernle32DLL: Ok, now it is clearer once I saw the wsdl, so you were expecting the "message" declaration to be transformed to classes? It is not how it works, at least with jaxb, but then after a quick search with google ("spring ws message multipart"), I found that: http://stackoverflow.com/questions/15276618/how-can-i-send-a-multiple-part-message-in-soap-spring-ws and it basically said that it is not so regular to have multipart, even though it could be, and that you could use cxf that supports multipart…

**Comment by highsource** [comment]
Here's how I see it.

`maven-jaxb2-plugin` "just" makes XJC callable in Maven builds. The scope of the plugin is to call XJC correctly, passing the parameters as configured.

If at the end you don't get the things generated you'd like to, there are three reasons for this:

* The plugin was not configured correctly.
* The plugin did not pass the configuration to XJC correctly.
* The XJC does not generate things according to your expectations.

The second point would be a bug in the plugin, which we'd fix. But there is yet no evidence that it is a case here. A control question would be - which arguments *should* be passed to XJC for this to work and which arguments *are* passed to XJC by the plugin?

I think it's either the first or (more likely) the third case. But I still did not quite understood what exactly is a problem. What would you expect to be generated and what was not generated?

My suggestuin would be that you create and commit (via PR) a demo project here:

https://github.com/highsource/maven-jaxb2-plugin-support

Under `g/gksst`.

And explain, which items would you like to see generated (and which are not). That would be something to get started with. Do you miss classes for elements like `GkSstServer_getShippedOrderListResponse`? I think what you really need is `wsdl2java`, bot just XJC.

**Comment by Kernle32DLL** [comment]
Sorry for coming back to this so late. The project was under a lot of pressure, so we had no time to follow the issue any further. And so we resorted to putting the missing service calls into the types section as described in the in initial post.

To elaborate on the actual problem: jaxb2 (or xjc for this matter) only generates java classes that are present in the \<types/> section of the provides wsdl file. This is now also stated in the spring tutorial I mentioned originally (but was not back then): https://spring.io/guides/gs/consuming-web-service/

> JAXB provides an easy means to generate Java classes from a WSDL (or rather: the XSD contained in the \<Types/> section of the WSDL)

While this works perfectly fine with the WSDL in the example, it does not with our mentioned WSDL. While the WSDL in question contains responses and other complex data types part of the service in said \<types/> section, the actual "service calls" are not present.

An example for this is "getAvailabeCompanyList" (don't mind the wrong spelling. It really is like this in the WSDL file -.-). This yields a "getAvailabeCompanyListResponse", which in turn contains a "companyList". The latter is contained as a complex type in the \<types/> section, the former two are not. This results in jaxb2 generating a "companyList" java class, but neither "getAvailabeCompanyList" nor "getAvailabeCompanyListResponse". Which effectively means, that "getAvailabeCompanyList" cannot be used. This is true for **all** operations in said WSDL, so no communication whatsoever is possible.

As above is only true for the linked WSDL, and not the WSDL used in the Spring examples, I presume this is not an issue of jaxb2, but the definition of the file itself (which sadly we have no control over). So - I'm closing this issue. Feel free to open it again, if my elaboration was incorrect. Thanks for the support anyway!

**Comment by bhatshahid123** [comment]
ConnectionConfig and ReadResult Classes are missing, so how can I resolve this problem?

**Comment by AleksandarTokarev** [comment]
@kernle32dll Were you able to resolve it? The WSDL that we are supposed to use does not contain ComplexTypes - therefore classes are not generated.
