### ISSUE TITLE
Catalog can't refer to their container maven artefact

### ISSUE THREAD

**Issue by victornoel** [highsource/maven-jaxb2-plugin#56]
Hi,

If a maven artefact (here easywsdl-schema) contains a catalog (and use it in the configuration of maven-jaxb2-plugin) and this catalog refers to this very same maven artefact, I get the following error in the console: 
```
26/08/2015, 10:36:33 CEST: [ERROR] Error resolving dependency resource [Dependency {groupId=org.ow2.easywsdl, artifactId=easywsdl-schema, version=null, type=jar, classifier=null, resource=schema/xml.xsd}].
26/08/2015, 10:36:33 CEST: [ERROR] Failed to resolve systemId [maven:org.ow2.easywsdl:easywsdl-schema!/schema/xml.xsd] as dependency resource. Returning parent resolver result [maven:org.ow2.easywsdl:easywsdl-schema!/schema/xml.xsd].
```

Shouldn't this work?

**Comment by highsource** [comment]
I'm not quite sure how to make this work.
During the build, the JAR is not built yet, so we can't access resources inside JAR.
Code generation is normally done in `generate-sources` phase. This means that resources aren't necessarily built (i.e. generated/filtered/copied to target dir) yet by then.

So basically the only option is to search all the resource directories. Which will normally work, but is not correct (consider the generated/filtered resources).

This is why I don't think it would be a right thing to implement.

**Comment by victornoel** [comment]
I see yes, this makes sense, is that why you made different artefacts in w3c-schemas: one for containing the resources and the others to generate the sources from these schemas?

What is strange is that in the error message it says "Returning parent resolver result [maven:org.ow2.easywsdl:easywsdl-schema!/schema/xml.xsd]", as if it could actually access schema/xml.xsd from the maven artefacts. But you just said it is not the case… and code generation works even with the error message. Why is that?

**Comment by highsource** [comment]
Resolvers only work with URIs, so this is basically just string manipulation, it doesn't say anything about actual accessibility of the resource, I think.

Why it works with an error... I'm not sure. Maybe some try-catch story (try to access but if failed then ignore) which still logs the error is the try clause. It's hard to say without tracing and I don't think that is worth the effort at the moment.

**Comment by victornoel** [comment]
Yep, ok :)

**Comment by highsource** [comment]
I think we can't do here much so I'll close it.
