### ISSUE TITLE
Support proxy configuration.

### ISSUE THREAD

**Issue by highsource** [highsource/maven-jaxb2-plugin#58]
See #50.

**Comment by highsource** [comment]
Docs:
* https://github.com/highsource/maven-jaxb2-plugin/wiki/Configuring-Proxies
* https://github.com/highsource/maven-jaxb2-plugin/wiki/Configuration-Cheat-Sheet

**Comment by highsource** [comment]
@Dawuid I've applied the PR and reworked it a bit. For the better backwards compatibility I've added a `useActiveProxyAsHttpproxy` parameter. If you want to pass Maven proxy setting to XJC, you'd need to set it to `true` (default is `false`).

I also think that you shouldn't need proxies as you shouldn't compile remote resources. Make local copies and use catalogs to rewrite URLs.

**Comment by Dawuid** [comment]
Thank you very much.

I understand your solutions to avoid proxy use, but I feel that (the solutions) are kind of hacks. You can duplicate a public resource (like jee schemas for example) in a local storage and use catalogs (if you are in a development team, such local storage must be synchronized between them) or you can use them from original URL source (if available and trusted). In some projects I used a mixture of both solutions, that's the argument for proxy feature.

**Comment by highsource** [comment]
What I'm normally doing is first creating a `schemas` project which contains these public resources and then use schemas from this artifact in other modules. This is how [ogc-schemas](https://github.com/highsource/ogc-schemas) project is structured. In this case "synchronizing local storage" is done via Maven mechanisms, you don't need to invent anything here.  
So I won't call this "hacks", this is a direct purpose of catalogs.
