### ISSUE TITLE
"if-exists" added only to "package" bindings but not to "class"bindings in episode file

### ISSUE THREAD

**Issue by pronchakov** [highsource/maven-jaxb2-plugin#61]
```<addIfExistsToEpisodeSchemaBindings>``` settings adds ```if-exists``` attribute not to all ```<bindings>``` elements.

For example, after generating episide file:
```XML
<bindings xmlns:tns="{my-tns}" if-exists="true" scd="x-schema::tns">
    <schemaBindings map="false">
      <package name="{my-package-name}"/>
    </schemaBindings>
    <bindings scd="~tns:{my-element}">
      <class ref="{my-element-class}"/>
    </bindings>
    <bindings scd="~tns:{my-element-2}">
      <class ref="{my-element-class}"/>
    </bindings>
</bindings>
```

But when I use this episode file in generating other classes, I get **"didnt match any schema component"** error if not all {my-element*} elements were used in XSD's that are being processing.

I didn't found any other solutions than to add ```if-exists="true"``` to bindings with ```<class>``` element inside, so it would be like:
```XML
<bindings xmlns:tns="{my-tns}" if-exists="true" scd="x-schema::tns">
    <schemaBindings map="false">
      <package name="{my-package-name}"/>
    </schemaBindings>
    <bindings if-exists="true" scd="~tns:{my-element}">
      <class ref="{my-element-class}"/>
    </bindings>
    <bindings if-exists="true" scd="~tns:{my-element-2}">
      <class ref="{my-element-class}"/>
    </bindings>
</bindings>
```

If I wrong about correctness of this solution, please advise me a better way or some reasons that that kind of way is wrong.
If I'm not, maybe ```addIfExistsToEpisodeSchemaBindings.xslt``` should be fixed?

I can send a pull request if it will need.

**Comment by highsource** [comment]
I think you're right. Please send the PR, would you? Thanks!
