### ISSUE TITLE
Incomplete generation <xs:element ... type=...>

### ISSUE THREAD

**Issue by computerlyrik** [highsource/maven-jaxb2-plugin#63]
I have a wsdl file like follows:

```
<wsdl:definitions  .... >
       <wsdl:types>
              <xs:schema elementFormDefault="qualified" attributeFormDefault="qualified"   targetNamespace="..."  xmlns:xs="http://www.w3.org/2001/XMLSchema">
                    <xs:element name="someRequest" type="ws:someRequestType" />
                    <xs:element name="someResponse" type="ws:someResponseType" />
 .....
```

the ```someRequestType``` and ```someResponseType```  are later defined as ```<xs:complexType>```

But they are never generated as classes with ```@XmlRootElement```

So i cannot use them in the request, neither marshalling the response.

Why is this?

I am following https://spring.io/guides/gs/consuming-web-service/

**Comment by highsource** [comment]
XJC does not always generate classes for the root elements. In such cases you shoould use `JAXBElement<SomeRequestType>` etc. Also check your `ObjectFactory`.

Why is this - please address this question to the JAXB RI team. This is not specific to the Maven plugin which this project is about.

**Comment by highsource** [comment]
See this question on SO:

**Comment by computerlyrik** [comment]
I just tell the marshaller which package to use.

My issue is that the class is not generated.

**Comment by computerlyrik** [comment]
how do i enable simple binding mode within the plugin?

**Comment by computerlyrik** [comment]
Using the Example 1 from https://jaxb.java.net/nonav/2.2.3u1/docs/api/javax/xml/bind/annotation/XmlRootElement.html

The plugin does not (reverse) generate the class as expected!

**Comment by computerlyrik** [comment]
ALWAYS USE 

```
<jaxb:bindings xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.0" xmlns:xjc= "http://java.sun.com/xml/ns/jaxb/xjc" jaxb:extensionBindingPrefixes="xjc">
<jaxb:globalBindings>
<xjc:simple/>
</jaxb:globalBindings>
</jaxb:bindings> 
```

Was the solution for me.

**Comment by highsource** [comment]
Please refer to the SO question I've posted above:

http://stackoverflow.com/questions/819720/no-xmlrootelement-generated-by-jaxb

XJC does not always generate classes for root elements, so this *is* the expected and corrected behaviour for the plugin as well. The plugin just calls the XJC.

As I pointed out, you can switch it on via `xjc:simple`. You'll need to [specify a bindings file](https://github.com/highsource/maven-jaxb2-plugin/wiki/Specifying-What-To-Compile#specifying-bindings) this one:

```xml
<jaxb:bindings
    xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" 
    jaxb:version="2.0" 
    xmlns:xjc= "http://java.sun.com/xml/ns/jaxb/xjc" 
    jaxb:extensionBindingPrefixes="xjc"> 

    <jaxb:globalBindings> 
        <xjc:simple/>
    </jaxb:globalBindings> 
</jaxb:bindings>
```

Whether or not XJC should or should not generate classes for the root elements is strictly not in scope of this project.

**Comment by computerlyrik** [comment]
Yup. tnx. staying with this wonderful Plugin.
