### ISSUE TITLE
How to not separate numbers from letter in the resulting property name.

### ISSUE THREAD

**Issue by fcontreras** [highsource/maven-jaxb2-plugin#64]
I have a

```xml
<xs:simpleType name="NamesType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="CARLOS" />
        <xs:enumeration value="CARLOS2" />
    </xs:restriction>
</xs:simpleType>
```

The result is a 

```java
public enum NamesType { 
    ...
    CARLOS("CARLOS"),
    @XmlEnumValue("CARLOS2")
    CARLOS_2("CARLOS2"),
    ...
}
```

Is there a way to avoid the underscore in the second enum value?
Thanks

**Comment by highsource** [comment]
This question is out of the scope here as it's not the Maven plugin functionality.
Please ask on StackOverflow. Hint: google `jaxb:typesafeEnumMember`.

**Comment by fcontreras** [comment]
Thanks.. managed to solve it with some google results from your suggestion.
