### ISSUE TITLE
Generate property level javadoc

### ISSUE THREAD

**Issue by jasonCodesAway** [highsource/maven-jaxb2-plugin#65]
Hello,

Great work on this plugin, thank you! :+1: 

Assuming I have this defined in XSD:
```
<xs:complexType name="Product">
    <xs:sequence>
        <xs:element name="SerialNumber" type="xs:string" minOccurs="1">
            <xs:annotation>
                <xs:documentation>Each product has one or more serial numbers</xs:documentation>
            </xs:annotation>
        </xs:element>
    </xs:sequence>
</xs:complexType>
```

This is the JAVA that gets generated:

```java
    @XmlElement(name = "SerialNumber")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-17T03:23:08-05:00", comments = "JAXB RI v2.2.11")
    protected String serialNumber;

    /**
     * Gets the value of the serialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-17T03:23:08-05:00", comments = "JAXB RI v2.2.11")
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * Sets the value of the serialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-11-17T03:23:08-05:00", comments = "JAXB RI v2.2.11")
    public void setSerialNumber(String value) {
        this.serialNumber = value;
    }
```

How can I push the SerialNumber javadoc (e.g. "Each product has one or more serial numbers") through to the generated JAVA documentation on the getters, setters, and property javadoc?

Thanks & Cheers from Florida. 

Jason

**Comment by highsource** [comment]
Hi,

this is not in scope of the Maven plugin as it "just wraps" XJC.

But check this SO question:

http://stackoverflow.com/questions/1650249/how-to-make-generated-classes-contain-javadoc-from-xml-schema-documentation

I can also imaging an XJC plugin which processes the "usual" `xs:documentation` instead of `jaxb:javadoc` but that would be also out of the scope here.

Best wishes,
Alexey

**Comment by jasonCodesAway** [comment]
Thanks for the update. I've voted for the appropriate issue here: https://java.net/jira/browse/JAXB-172. It was opened in 2006 and still hasn't been addressed!
