### ISSUE TITLE
Referring episode from transitive dependencies? 

### ISSUE THREAD

**Issue by jinahya** [highsource/maven-jaxb2-plugin#66]
Hi. Thank you for the great plugin.

I have `a-bind.jar` which compiles `a.xsd`.
I have `b-bind.jar` which compiles `b.xsd` which imports `a.xsd`.

Using episodes works fine so far.

And I have `c-bind.jar` which compiles `c.xsd` which imports both `a.xsd` and `b.xsd`.

A problem arises here.
I have to depends both `a-bind` and `b-bind` for using them in `<episodes>` which means I have to take a extra care for the `b-bind:version`.

Thanks.

**Comment by highsource** [comment]
Probably a duplicate for #52.

What is exactly the problem? That you have to specify the version in `episodes/episode` for `b-bind` or that it does not work with `useDependenciesAsEpisodes`?

**Comment by jinahya** [comment]
Thank you.
`<useDependenciesAsEpisodes>true</useDependenciesAsEpisodes>` works like a charm.
It seems the plugin takes care of transitive dependencies as well.
