### ISSUE TITLE
apply the magic from this plugin to jaxws-plugin please :-)

### ISSUE THREAD

**Issue by heymjo** [highsource/maven-jaxb2-plugin#70]
Hi,

It would be great if you could transform the jaxws-maven-plugin in the same way as you did with the jaxb2 plugin, and actually make it usable for everything beyond HelloService.wsdl ...

Not being able to grab catalogs and episodes from dependency resources is such a pain !

**Comment by highsource** [comment]
Well, I understand you. :) But I'm not sure I'll be able to develop and support another plugin.

**Comment by highsource** [comment]
I'm sorry.

**Comment by heymjo** [comment]
no worries i understand, was probably just venting some frustration :-)

**Comment by highsource** [comment]
Yes, I can understand that. And thanks for your feedback. :)
