### ISSUE TITLE
Plugin only generates the first listed execution when using multiple schemas configuration

### ISSUE THREAD

**Issue by highsource** [highsource/maven-jaxb2-plugin#78]
https://java.net/jira/browse/MAVEN_JAXB2_PLUGIN-86

**Comment by mheidt** [comment]
Hello,

I am facing this issue.
I have two executions in the pom:

setting the configuration values
schemaDirectory
schemaIncludes
bindingIncludes

In the jxb,
I am using an annox:annotate to get a @XmlRootElement with success

But the
<jaxb:schemaBindings>
            <jaxb:package>com.lhsystems.cute.localparameter</jaxb:package>
</jaxb:schemaBindings>
doesn't work...I have to use generatePackage in the pom, to get a package.

As I said, only the first execution is built.

[INFO] Latest timestamp of the source resources is [2017-03-01 18:00:30.000], ealiest timestamp of the target resources is [2017-03-01 18:00:34.000].
[INFO] Sources are up-to-date, XJC will be skipped.

I got it working with older plugin versions like jaxb2-maven-plugin. But in this casee I can't use annox:annotation if I am right.

Kind regards,
Markus

**Comment by mheidt** [comment]
<plugin>
                <groupId>org.jvnet.jaxb2.maven2</groupId>
                <artifactId>maven-jaxb22-plugin</artifactId>
                <version>0.13.1</version>
                <executions>
                    <execution>
                        <id>config</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <schemaDirectory>${project.basedir}/src/main/resources/schema</schemaDirectory>
                            <schemaIncludes>
                                <schemaInclude>**/config.xsd</schemaInclude>
                            </schemaIncludes>
                            <bindingIncludes>
                                <bindingInclude>config.xjb</bindingInclude>
                            </bindingIncludes>

                        </configuration>
                    </execution>
                    <execution>
                        <id>local-parameter</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <schemaDirectory>${project.basedir}/src/main/resources/schema</schemaDirectory>
                            <schemaIncludes>
                                <schemaInclude>**/local-parameter.xsd</schemaInclude>
                            </schemaIncludes>
                            <bindingIncludes>
                                <bindingInclude>local-parameter.xjb</bindingInclude>
                            </bindingIncludes>

                        </configuration>
                    </execution>

                </executions>

                <configuration>
                    <strict>true</strict>
                    <verbose>false</verbose>
                    <extension>true</extension>
                    <removeOldOutput>false</removeOldOutput>
                    <cleanPackageDirectories>false</cleanPackageDirectories>
                    <episode>false</episode>
                    <bindingDirectory>${project.basedir}/src/main/xjb</bindingDirectory>
                    <args>
                        <arg>-Xannotate</arg>
                    </args>
                    <plugins>
                        <plugin>
                            <groupId>org.jvnet.jaxb2_commons</groupId>
                            <artifactId>jaxb2-basics</artifactId>
                            <version>1.11.1</version>
                        </plugin>
                        <plugin>
                            <groupId>org.jvnet.jaxb2_commons</groupId>
                            <artifactId>jaxb2-basics-annotate</artifactId>
                            <version>1.0.2</version>
                        </plugin>
                    </plugins>
                </configuration>
            </plugin>

**Comment by mheidt** [comment]
I solved my problem by only using one execution and merged the two xjb into one.

**Comment by highsource** [comment]
You should use separate target directories for separate executions, it is documented:

https://github.com/highsource/maven-jaxb2-plugin/wiki/Use-Separate-Target-Directories-for-Separate-Executions
