### ISSUE TITLE
accessExternalSchema option is ignored

### ISSUE THREAD

**Issue by rdicroce** [highsource/maven-jaxb2-plugin#81]
In my POM, I have

`<accessExternalSchema>none</accessExternalSchema>`

But with verbose logging turned on, I see

[INFO] optionsConfiguration:OptionsConfiguration [specVersion=2.2
...
 accessExternalSchema=all

Looks like this field is missing a Property annotation, so Maven is not binding the value.

**Comment by highsource** [comment]
Should be fixed now. Indeed, an annotation was missing. However, you'll probably need to at least allo `file`.
