### ISSUE TITLE
workaround for xjc Java 8 bug 

### ISSUE THREAD

**Issue by hesoun** [highsource/maven-jaxb2-plugin#84]
Hi,

as you probably know, there is a bug in xjc for Java 8 [JAXB-986](https://java.net/jira/browse/JAXB-986) which is adding `@XmlSchemaType(name = "anySimpleType")` annotation to generated fields when xml element for this field reference extended simple type by name. 
This will cause **ClassCastException** when marshalling given type's object.

One workaround is to change the reference to inline type in your XSD but you have to change your XSD.

Would it be possible to incorporate some kind of workaround into your plugin that will delete this wrongly generated annotations?

**Comment by highsource** [comment]
Hi,

I think the best would be to write an XJC plugin for that an then I could
turn it on automatically in the Maven plugin.
Open for a PR.

Best wishes,
Alexey

**Comment by vinayshankar** [comment]
@cztorgar Can you explain the workaround that you mention? 
@highsource I notice that there exists a xjc plugin (http://repo1.maven.org/maven2/org/apache/cxf/xjcplugins/cxf-xjc-bug986/3.0.3/). How would I go about using that?

**Comment by highsource** [comment]
As usual:

**Comment by highsource** [comment]
Since there's an XJC plugin fix the problem I think this is the way to go.
I don't think it's appropriate to integrate this plugin in `maven-jaxb2-plugin`. If we follow this path, `maven-jaxb2-plugin` will end up being a conglomerate of fixes for XJC.
