### ISSUE TITLE
Multiple executions using the same target folder

### ISSUE THREAD

**Issue by renholm** [highsource/maven-jaxb2-plugin#87]
Dear all,

For reasons out of my control I need to have multiple executions to be able to have different target packages (`generatePackage`). Using multiple executions works fine except for that I cannot get the plugin to use the same target directories (`generateDirectory`) for all executions. The directory looks to be emptied in the start of an execution so that the previous result is removed. I've tried to set `cleanPackageDirectories` to `false` without any effect. Bug or how should I do this?

**Comment by highsource** [comment]
Use separate target directories for separate executions.

https://github.com/highsource/maven-jaxb2-plugin/wiki/Use-Separate-Target-Directories-for-Separate-Executions

You can't use the same directory for multiple executions.

**Comment by renholm** [comment]
@highsource Sorry, missed that! 

I would like to use a binding file but the schemas are missing namespaces, any alternative to the multiple executions in that case?

**Comment by highsource** [comment]
For no namespaces - probably not. Have to use multiple executions or separate projects.
