### ISSUE TITLE
Generated types discrepancy for substitution groups in Java 8 and 7

### ISSUE THREAD

**Issue by hebrayah** [highsource/maven-jaxb2-plugin#89]
There was discrepancy for plugin versions prior to 0.11.0 for generation Java types from XSD substiution groups - running under Java 7 Dependent fields had been generated as internal classes for top level class - in java 8 - its internal type of XSD type really belonging this field.
Plugin version 0.11.0 causes that in both JDK versions we are getting the same result and its unfortunately the same result as for Java 8 - but I need for compatibility reasons have output as for JDK 7.

**Comment by highsource** [comment]
I fail to understand the problem from the provided description. Please provide a reproducing test case (as a pull request). What is being generated at the moment, why do you think it's wrong and what would you like to have generated? Specifically.

**Comment by hebrayah** [comment]
When i will be in office i will cut out schema pieces to show this.

I don't think it's wrong - i think you have fixed problem - different
output from different JDK 7 vs 8 - problem is that i cannot use newest
plugin ( with if-exist feature ) with our schema package because its built
with JDK 7 and it becomes backward incompatible.
Firstly i thought that problem is with 0.13.1 only - but today i checked
that it differs between 0.10.0 and 0.11.0

Greetings
Marcin

2016-03-15 20:48 GMT+01:00 Alexey Valikov <notifications@github.com>:

**Comment by highsource** [comment]
No reply - closing.
