### ISSUE TITLE
Plugin throws NullPointerException in specific modules configuration

### ISSUE THREAD

**Issue by FcrNah** [highsource/maven-jaxb2-plugin#90]
Please see attached Maven project.
[spring-model.zip](https://github.com/highsource/maven-jaxb2-plugin/files/210439/spring-model.zip)

I'm working on generation of classes from *spring-integration* schemas.
For the purpose of this example I've created Maven project which generates following xsds:
- spring-beans-4.2.xsd
 - spring-integration-4.2.xsd
    - spring-integration-file-4.2.xsd
    - spring-integration-mail-4.2.xsd

There are 5 modules:
- *spring-all* - this project successfully builds whole schema structure, I've changed  `schemaLocation` attribute in import tag manually. This module created to show that there is no errors in schemas.

The rest four modules contain described four schemas one by one. Schema references substitutes with Oasis Xml catalog files.
- *spring-beans-model* - builds successfully.
- *spring-integration-model* - references *spring-beans-model*, builds successfully.
- *spring-integration-mail-model* - references *spring-beans-model* and *spring-integration-model*, builds successfully. This module created to show that this isn't references issue.
- *spring-integration-file-model* - references *spring-beans-model* and *spring-integration-model*, build fails with NPE. See stack trace in attached file. [FullStacktrace.txt](https://github.com/highsource/maven-jaxb2-plugin/files/210438/FullStacktrace.txt)

I found out that this issue disappears if I comment out first `xsd:element` section in spring-integration-file-4.2.xsd

There are also xjb bindings in attached modules, not connected to this issue.

**Comment by highsource** [comment]
Please send me a PR of your project in https://github.com/highsource/maven-jaxb2-plugin-support/s/spring-integration.

**Comment by FcrNah** [comment]
https://github.com/highsource/maven-jaxb2-plugin-support/pull/2
Thats my first time, I'm not sure if i did it right..

**Comment by highsource** [comment]
PR is fine, thank you. Reproduced.

**Comment by highsource** [comment]
This appears to be a bug in XJC, just reported it:

https://java.net/jira/browse/JAXB-1097

As a workaround, try the [JAXB2 Simplify Plugin](https://github.com/highsource/jaxb2-basics/wiki/JAXB2-Simplify-Plugin) on your property (the choice property in `inbound-channel-adapter`).
Otherwise compile it without episodes, all schemas at once.
