### ISSUE TITLE
Set Methods are not generated for Anonymous Complex Type

### ISSUE THREAD

**Issue by guru2228** [highsource/maven-jaxb2-plugin#91]
hi, i have a XSD as below and i use the plugin to generate the JAXB Class which does not have any methods other than toString, hashCode and equals. Please refer the second screenshot. Please help me how to generate the methods.
![image](https://cloud.githubusercontent.com/assets/929441/14417460/8104bc4c-ff7b-11e5-9e98-d98b4d7aaf88.png)
![image](https://cloud.githubusercontent.com/assets/929441/14417537/7782c30c-ff7c-11e5-8da9-c0c98f6fa752.png)

**Comment by highsource** [comment]
* Look in the `CustomerAccountType`, your property methods are probably there.
* Your question is clearly out of the scope of this project.

**Comment by guru2228** [comment]
Sorry for not including the screenshot for CustomerAccountType where i have the the below comments

/**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "CustomerPurchase" is used by two different parts of a schema. See: 
     * line 28 of file:/C:/00_PROJECTS/99_workspace/c360-canonical-models/src/main/xsd/com/schema/physical/customeraccount/v9_03/customeraccount.xsd
     * line 26 of file:/C:/00_PROJECTS/99_workspace/c360-canonical-models/src/main/xsd/com/schema/canonical/customeraccount/v9_03/customeraccount.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the rest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRest().add(newItem);
     * </pre>
     * 

![image](https://cloud.githubusercontent.com/assets/929441/14481244/beb6899a-00f6-11e6-8d01-50a8317efa48.png)
