### ISSUE TITLE
How do I use multiple plugins?

### ISSUE THREAD

**Issue by mbucc** [highsource/maven-jaxb2-plugin#93]
I want to use both the krasa-jaxb-tools and jaxb2-basics plugins.

It works fine with just the krasa-jaxb-tools plugin.   But after changing the pom.xml like so:

```diff
--- pom.xml	3 May 2016 13:35:45 -0000	1.7.2.3
+++ pom.xml	3 May 2016 14:18:53 -0000
@@ -65,7 +65,6 @@
         <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-compiler-plugin</artifactId>
       </plugin>
-
       <plugin>
         <groupId>org.jvnet.jaxb2.maven2</groupId>
         <artifactId>maven-jaxb2-plugin</artifactId>
@@ -81,6 +80,7 @@
               <generatePackage>com.isone.transmart.bind</generatePackage>
               <args>
                 <arg>-XJsr303Annotations</arg>
+                <arg>-Xequals</arg>
               </args>
               <plugins>
                 <plugin>
@@ -88,5 +88,10 @@
                   <artifactId>krasa-jaxb-tools</artifactId>
                   <version>1.4</version>
                 </plugin>
+                <plugin>
+                  <groupId>org.jvnet.jaxb2_commons</groupId>
+                  <artifactId>jaxb2-basics-runtime</artifactId>
+                  <version>0.11.0</version>
+                </plugin>
               </plugins>
             </configuration>
```

`mvn compile` generates the following error:

[ERROR] Failed to execute goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.3:generate (default) on project transmart-schema: Error parsing the command line [[-XJsr303Annotations, -Xequals, -episode, /home/mbucciarelli/src/workspace/warp/transmart/transmart-schema/target/generated-sources/xjc/META-INF/sun-jaxb.episode]]: unrecognized parameter -Xequals -> [Help 1]

How do I configure this properly?

**Comment by highsource** [comment]
You should use:

```
                        <plugin>
                            <groupId>org.jvnet.jaxb2_commons</groupId>
                            <artifactId>jaxb2-basics</artifactId>
                            <version>...</version>
                        </plugin>
```

Not the `jaxb2-basics-runtime`. Please see the docs:

https://github.com/highsource/jaxb2-basics/wiki/Using-JAXB2-Basics-Plugins#using-jaxb-plugins-with-maven

**Comment by mbucc** [comment]
From the referenced page:
>
> you don't need to define the dependencies,
> Maven will take care of dependency resolution
>

This was not my case.  I got this compile error for each generated Java class:

     error: package org.jvnet.jaxb2_commons.lang does not exist

Adding the following dependency entry to the pom (in the  `<dependencies>` section) fixed it:
```xml

    <dependency>
      <groupId>org.jvnet.jaxb2_commons</groupId>
      <artifactId>jaxb2-basics</artifactId>
      <version>0.11.0</version>
    </dependency>
```

Or is that what you meant by:

> Add the plugin library available into the XJC
> classpath (including all the required dependencies).

?

**Comment by highsource** [comment]
@mbucc Dependencies of the JAXB2 plugins used during the code generation and dependencies of the generated code are completely different things.
