### ISSUE TITLE
Version 0.12.2 and later causes maven error in Eclipse Mars.2

### ISSUE THREAD

**Issue by wkrick** [highsource/maven-jaxb2-plugin#95]
When I try to use version 0.12.2 or later in my project, I get this Maven error in Eclipse...

`Execution default of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.3:generate failed: A required class was missing while executing org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.3:generate: com/sun/xml/bind/api/ErrorListener
`

Version 0.12.1 and earlier do not have this error.

**Comment by highsource** [comment]
Duplicate for #69.
