### ISSUE TITLE
Project Local namespace resolution depends on alphanumeric sorting of xsd file names.

### ISSUE THREAD

**Issue by Newtopian** [highsource/maven-jaxb2-plugin#98]
I have a project in which there are multiple xsd files each defining specific aspects of the data model.  All files are in the same project and in the default location (src/main/resources/*.xsd).

base.xsd -> defines some base types
event.xsd -> defines some more advanced types and imports base.xsd
binary.xsd -> defines some specific implementation and imports both base.xsd and event.xsd

Before adding binary.xsd code generation worked like a charm, even added some bindings to have the classes implement interfaces and averything was good.  Namespace resolving in event.xsd was not an issue.

When adding binary.xsd a first type that only depends on base.xsd and it's associated bindings, everything again worked fine.

However when adding a second type that depends on event.xsd the code generation failed as it could not resolve the import event.xsd.

After some fidling around I found that renaming the files such that their alpha-numeric ordering coincides with the dependency tree everything again worked fine (with no other changes).
the renamed files became :

1base.xsd
2event.xsd
3binary.xsd

These are the only three xsd files in the project and they do not import anything outside the project itself.

I would have expected the namespace resolver to be able to run through the complete list of xsd before failing rather than just getting the files that falls before on the list.

**Comment by highsource** [comment]
This seems to be an issue with XJC, not the maven plugin.

**Comment by Newtopian** [comment]
ha!  did not think of checking there, I'll give it a go see what comes up.  Makes sense though.

**Comment by Newtopian** [comment]
Yup... found pretty much the same situation as I was in right here : 

https://java.net/jira/browse/JAXB-906

**Comment by highsource** [comment]
Closing as `invalid` as it is apparently an XJC problem.
