### ISSUE TITLE
otherDepends configuration does not support glob patterns

### ISSUE THREAD

**Issue by akloeber** [highsource/maven-jaxb2-plugin#99]
We are using the `otherDepends` configuration entry to work around the fact that changes in imported schema files are not detected by the plugin's Up-To-Date check as described at https://github.com/highsource/maven-jaxb2-plugin/wiki/Up-To-Date-Checks#limitations.

The configuration cheat sheet at https://github.com/highsource/maven-jaxb2-plugin/wiki/Configuration-Cheat-Sheet and tag name `<pattern>` suggest that glob patterns are supported but they do not work. The following configuration:

```
<otherDepends>
  <pattern>src/main/resources/xsd/api/v1.0.0/*.xsd</pattern>
</otherDepends>
```

produces:

```
[ERROR] File [<PROJECT_DIR>/src/main/resources/xsd/api/v1.0.0/*.xsd] does not exist.
```

whereas this works:

```
<otherDepends>
  <pattern>src/main/resources/xsd/api/v1.0.0/api.xsd</pattern>
</otherDepends>
```

To make sure that even changes in imported schema files are recognized we would like to use a pattern like `src/main/resources/xsd/**/*.xsd` instead of listing every imported file individually.

**Environment:**
maven-jaxb2-plugin 0.13.1
Maven 3.0.5
Java 1.8.0_65

**Comment by highsource** [comment]
This should be fixed now. You can use:

```
							<otherDependsIncludes>
								<pattern>src/main/resources/*.xsd</pattern>
							</otherDependsIncludes>
```

Also `otherDependsExcludes`.

The old `otherDepends` setting will be marked deprecated and kept as is for backwards compatibility.
